export const pagoConfig = {
  modulo: "Pagos",
  titulo: "Listado de Pagos",
  entidad: "pagos",
  pk: "IDPAGOMENSUALIDAD",
  columnas: [
    { campo: "ESTUDIANTE_NOMBRE", etiqueta: "Estudiante", ordenable: true },
    { campo: "ESTUDIANTE_DNI", etiqueta: "DNI", ordenable: false },
    { campo: "PLAN_NOMBRE", etiqueta: "Plan", ordenable: false },
    { campo: "MONTO", etiqueta: "Cuota", tipo: "decimal", ordenable: true },
    { campo: "MORA", etiqueta: "Mora", tipo: "decimal", ordenable: false },
    { campo: "TOTAL_COBRADO", etiqueta: "Total cobrado", tipo: "decimal", ordenable: false },
    { campo: "METODOPAGO_TITULO", etiqueta: "Método", ordenable: false },
    { campo: "FECHAPAGO", etiqueta: "Fecha", tipo: "fecha", ordenable: true },
    { campo: "OBSERVACIONES", etiqueta: "Detalle", ordenable: false },
  ],
  camposEdicion: [
    {
      campo: "ESTUDIANTE_NOMBRE",
      etiqueta: "Estudiante",
      control: "text",
      bloqueado: true,
    },
    {
      campo: "PLAN_NOMBRE",
      etiqueta: "Plan",
      control: "text",
      bloqueado: true,
    },
    {
      campo: "MONTO",
      etiqueta: "Monto aplicado a la cuota",
      control: "number",
      obligatorio: true,
    },
    {
      campo: "MORA",
      etiqueta: "Mora",
      control: "number",
      ayuda: "Monto extra por pago fuera de fecha. No reduce el saldo de la cuota.",
    },
    {
      campo: "IDMETODOPAGO",
      etiqueta: "Método de pago",
      control: "select",
      catalogo: "metodosPago",
      obligatorio: true,
    },
    {
      campo: "FECHAPAGO",
      etiqueta: "Fecha de pago",
      control: "date",
      obligatorio: true,
    },
    {
      campo: "OBSERVACIONES",
      etiqueta: "Detalle / observaciones",
      control: "textarea",
      full: true,
    },
  ],
};
