export const pagoConfig = {
  modulo: "Pagos",
  titulo: "Listado de Pagos",
  entidad: "pagos",
  pk: "IDPAGOMENSUALIDAD",
  columnas: [
    { campo: "ESTUDIANTE_NOMBRE", etiqueta: "Estudiante", ordenable: true },
    { campo: "PLAN_NOMBRE", etiqueta: "Plan", ordenable: true },
    { campo: "CUOTA_NUMERO", etiqueta: "N° Cuota", ordenable: true },
    { campo: "TOTAL", etiqueta: "Total", tipo: "decimal", ordenable: true },
    { campo: "DEUDA", etiqueta: "Deuda", tipo: "deudaCompletado", ordenable: true },
    { campo: "PAGADO", etiqueta: "Pagado", tipo: "decimal", ordenable: true },
    {
      campo: "FECHAINICIO_CUOTA",
      etiqueta: "Fecha",
      tipo: "rangoFecha",
      campoFin: "FECHAFIN_CUOTA",
      ordenable: true,
    },
  ],
  columnasDetalle: [
    { campo: "FECHAPAGO", etiqueta: "Fecha", tipo: "fecha", ordenable: false },
    { campo: "HORAPAGO", etiqueta: "Hora", tipo: "hora", ordenable: false },
    { campo: "MONTO", etiqueta: "Cuota", tipo: "decimal", ordenable: false },
    { campo: "MORA", etiqueta: "Mora", tipo: "decimal", ordenable: false },
    { campo: "TOTAL_COBRADO", etiqueta: "Total cobrado", tipo: "decimal", ordenable: false },
    { campo: "CUOTA_NUMERO", etiqueta: "N.º cuota", ordenable: false },
    { campo: "METODOPAGO_TITULO", etiqueta: "Método", ordenable: false },
  ],
  camposEdicion: [
    {
      campo: "ESTUDIANTE_NOMBRE",
      etiqueta: "Estudiante",
      control: "text",
      bloqueado: true,
    },
    {
      campo: "PLAN_NOMBRE",
      etiqueta: "Plan",
      control: "text",
      bloqueado: true,
    },
    {
      campo: "CUOTA_NUMERO",
      etiqueta: "N.º cuota",
      control: "text",
      bloqueado: true,
    },
    {
      campo: "MONTO_CUOTA",
      etiqueta: "Total de la cuota",
      control: "number",
      bloqueado: true,
    },
    {
      campo: "FECHAINICIO_CUOTA",
      etiqueta: "Inicio de la cuota",
      control: "date",
      bloqueado: true,
    },
    {
      campo: "FECHAFIN_CUOTA",
      etiqueta: "Fin de la cuota",
      control: "date",
      bloqueado: true,
    },
    {
      campo: "MONTO",
      etiqueta: "Monto aplicado a la cuota",
      control: "number",
      obligatorio: true,
    },
    {
      campo: "MORA",
      etiqueta: "Mora",
      control: "number",
      ayuda: "Monto extra por pago fuera de fecha. No reduce el saldo de la cuota.",
    },
    {
      campo: "IDMETODOPAGO",
      etiqueta: "Método de pago",
      control: "select",
      catalogo: "metodosPago",
      obligatorio: true,
    },
    {
      campo: "FECHAPAGO",
      etiqueta: "Fecha de pago",
      control: "date",
      obligatorio: true,
    },
    {
      campo: "OBSERVACIONES",
      etiqueta: "Detalle / observaciones",
      control: "textarea",
      full: true,
    },
  ],
};
