-- Convertido automáticamente desde db_scripts/29_07_2026/1.notas_importacion_tablas.sql
-- MySQL 8 — Academia 3.0

USE `AcademiaDB`;

/* ============================================================================
   Tablas importación de notas (Scantron / Excel)
   Ejecutar después de scripts 26_07_2026
   Fecha: 29/07/2026
   ============================================================================ */

IF OBJECT_ID('NOTA_IMPORTADA', 'U') IS NOT NULL DROP TABLE NOTA_IMPORTADA;
IF OBJECT_ID('NOTAS_IMPORTACION', 'U') IS NOT NULL DROP TABLE NOTAS_IMPORTACION;

CREATE TABLE IF NOT EXISTS NOTAS_IMPORTACION (
    IDIMPORTACION       INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOMBRE_ARCHIVO      VARCHAR(255) NOT NULL,
    FECHA_IMPORTACION   VARCHAR(20) NOT NULL,
    FECHA_EXAMEN        VARCHAR(8) NOT NULL,
    IMPORTADO_POR       VARCHAR(50) NULL,
    IDAULA              VARCHAR(50) NULL,
    TIPO_IMPORTACION    INT NOT NULL,
    TIPO_EXAMEN         VARCHAR(20) NOT NULL DEFAULT 'presencial',
    TIPO_AREA_ACADEMICA VARCHAR(10) NULL,
    ESTADO              VARCHAR(20) NOT NULL DEFAULT 'Activo',
    CONSTRAINT FK_NOTAS_IMPORTACION_USUARIO FOREIGN KEY (IMPORTADO_POR) REFERENCES USUARIO(IDUSUARIO),
    CONSTRAINT FK_NOTAS_IMPORTACION_AULA FOREIGN KEY (IDAULA) REFERENCES AULA(IDAULA)
);

CREATE TABLE IF NOT EXISTS NOTA_IMPORTADA (
    IDNOTA          INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    IDIMPORTACION   INT NOT NULL,
    IDUSUARIO       VARCHAR(50) NOT NULL,
    MODO            VARCHAR(20) NOT NULL DEFAULT 'presencial',
    PUNTAJE         DECIMAL(8,2) NOT NULL,
    PORCENTAJE      DECIMAL(8,2) NOT NULL,
    CORRECTAS       INT NOT NULL DEFAULT 0,
    INCORRECTAS     INT NOT NULL DEFAULT 0,
    NO_RESPUESTA    INT NOT NULL DEFAULT 0,
    DETALLE_AREAS   LONGTEXT NULL,
    ACT             DECIMAL(8,2) NOT NULL DEFAULT 0,
    HM              DECIMAL(8,2) NOT NULL DEFAULT 0,
    HV              DECIMAL(8,2) NOT NULL DEFAULT 0,
    ARIT            DECIMAL(8,2) NOT NULL DEFAULT 0,
    GEO             DECIMAL(8,2) NOT NULL DEFAULT 0,
    ALGE            DECIMAL(8,2) NOT NULL DEFAULT 0,
    TRIGO           DECIMAL(8,2) NOT NULL DEFAULT 0,
    LENGUA          DECIMAL(8,2) NOT NULL DEFAULT 0,
    LIT             DECIMAL(8,2) NOT NULL DEFAULT 0,
    PSI             DECIMAL(8,2) NOT NULL DEFAULT 0,
    CIV             DECIMAL(8,2) NOT NULL DEFAULT 0,
    HP              DECIMAL(8,2) NOT NULL DEFAULT 0,
    HU              DECIMAL(8,2) NOT NULL DEFAULT 0,
    GEO_L           DECIMAL(8,2) NOT NULL DEFAULT 0,
    ECO             DECIMAL(8,2) NOT NULL DEFAULT 0,
    FILO            DECIMAL(8,2) NOT NULL DEFAULT 0,
    FIS             DECIMAL(8,2) NOT NULL DEFAULT 0,
    QUI             DECIMAL(8,2) NOT NULL DEFAULT 0,
    BIO             DECIMAL(8,2) NOT NULL DEFAULT 0,
    CONSTRAINT FK_NOTA_IMPORTADA_IMPORT FOREIGN KEY (IDIMPORTACION) REFERENCES NOTAS_IMPORTACION(IDIMPORTACION),
    CONSTRAINT FK_NOTA_IMPORTADA_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
    CONSTRAINT UQ_NOTA_IMPORTADA_EST UNIQUE (IDIMPORTACION, IDUSUARIO)
);

CREATE INDEX IX_NOTAS_IMPORTACION_FECHA ON NOTAS_IMPORTACION (FECHA_EXAMEN, IDAULA, TIPO_IMPORTACION);
CREATE INDEX IX_NOTA_IMPORTADA_IMPORT ON NOTA_IMPORTADA (IDIMPORTACION);

SELECT 'Tablas NOTAS_IMPORTACION y NOTA_IMPORTADA listas.';
