-- ============================================================================
-- Renombrar MEMBRESIA → MENSUALIDAD, ASESOR → TUTOR (MySQL 8 — instalación nueva)
-- Ejecutar después de 26_07_2026/3.aula_catalogo_academia_vita.sql
-- ============================================================================

USE `AcademiaDB`;

SET FOREIGN_KEY_CHECKS = 0;

SET @col_asesor := (
    SELECT COUNT(*) FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'MEMBRESIA' AND COLUMN_NAME = 'ASESOR'
);
SET @sql_asesor := IF(@col_asesor > 0,
    'ALTER TABLE MEMBRESIA CHANGE COLUMN ASESOR TUTORLEGACY VARCHAR(150) NULL',
    'SELECT 1'
);
PREPARE stmt FROM @sql_asesor; EXECUTE stmt; DEALLOCATE PREPARE stmt;

RENAME TABLE NOTIFICACIONMEMBRESIA TO NOTIFICACIONMENSUALIDAD;
RENAME TABLE PAGOMEMBRESIA TO PAGOMENSUALIDAD;
RENAME TABLE MEMBRESIA TO MENSUALIDAD;
RENAME TABLE ASESOR TO TUTOR;

ALTER TABLE NOTIFICACIONMENSUALIDAD
    CHANGE COLUMN IDNOTIFICACIONMEMBRESIA IDNOTIFICACIONMENSUALIDAD VARCHAR(50) NOT NULL,
    CHANGE COLUMN IDMEMBRESIA IDMENSUALIDAD VARCHAR(50) NOT NULL;

ALTER TABLE PAGOMENSUALIDAD
    CHANGE COLUMN IDPAGOMEMBRESIA IDPAGOMENSUALIDAD VARCHAR(50) NOT NULL,
    CHANGE COLUMN IDMEMBRESIA IDMENSUALIDAD VARCHAR(50) NOT NULL;

ALTER TABLE MENSUALIDAD
    CHANGE COLUMN IDMEMBRESIA IDMENSUALIDAD VARCHAR(50) NOT NULL;

SET @col_idasesor := (
    SELECT COUNT(*) FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'MENSUALIDAD' AND COLUMN_NAME = 'IDASESOR'
);
SET @sql_idasesor := IF(@col_idasesor > 0,
    'ALTER TABLE MENSUALIDAD CHANGE COLUMN IDASESOR IDTUTOR VARCHAR(50) NULL',
    'SELECT 1'
);
PREPARE stmt FROM @sql_idasesor; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @col_tipo := (
    SELECT COUNT(*) FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'MENSUALIDAD' AND COLUMN_NAME = 'TIPOMEMBRESIA'
);
SET @sql_tipo := IF(@col_tipo > 0,
    'ALTER TABLE MENSUALIDAD CHANGE COLUMN TIPOMEMBRESIA TIPOMENSUALIDAD VARCHAR(100) NULL',
    'SELECT 1'
);
PREPARE stmt FROM @sql_tipo; EXECUTE stmt; DEALLOCATE PREPARE stmt;

ALTER TABLE TUTOR CHANGE COLUMN IDASESOR IDTUTOR VARCHAR(50) NOT NULL;

ALTER TABLE MENSUALIDAD
    ADD CONSTRAINT FK_MENSUALIDAD_PLAN FOREIGN KEY (IDPLAN) REFERENCES `PLAN`(IDPLAN),
    ADD CONSTRAINT FK_MENSUALIDAD_AULA FOREIGN KEY (IDAULA) REFERENCES AULA(IDAULA),
    ADD CONSTRAINT FK_MENSUALIDAD_TURNO FOREIGN KEY (IDTURNO) REFERENCES TURNO(IDTURNO),
    ADD CONSTRAINT FK_MENSUALIDAD_PROMOCION FOREIGN KEY (IDPROMOCION) REFERENCES PROMOCIONES(IDPROMOCION),
    ADD CONSTRAINT FK_MENSUALIDAD_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
    ADD CONSTRAINT FK_MENSUALIDAD_REGISTRADOPOR FOREIGN KEY (REGISTRADOPOR) REFERENCES USUARIO(IDUSUARIO),
    ADD CONSTRAINT FK_MENSUALIDAD_TUTOR FOREIGN KEY (IDTUTOR) REFERENCES TUTOR(IDTUTOR);

ALTER TABLE PAGOMENSUALIDAD
    ADD CONSTRAINT FK_PAGOMENSUALIDAD_MENSUALIDAD FOREIGN KEY (IDMENSUALIDAD) REFERENCES MENSUALIDAD(IDMENSUALIDAD),
    ADD CONSTRAINT FK_PAGOMENSUALIDAD_METODOPAGO FOREIGN KEY (IDMETODOPAGO) REFERENCES METODO_PAGO(IDMETODOPAGO),
    ADD CONSTRAINT FK_PAGOMENSUALIDAD_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO);

ALTER TABLE NOTIFICACIONMENSUALIDAD
    ADD CONSTRAINT FK_NOTIFMENSUALIDAD_MENSUALIDAD FOREIGN KEY (IDMENSUALIDAD) REFERENCES MENSUALIDAD(IDMENSUALIDAD),
    ADD CONSTRAINT FK_NOTIFMENSUALIDAD_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO);

SET FOREIGN_KEY_CHECKS = 1;

DROP PROCEDURE IF EXISTS usp_membresia_listar;
DROP PROCEDURE IF EXISTS usp_membresia_obtener;
DROP PROCEDURE IF EXISTS usp_membresia_insertar;
DROP PROCEDURE IF EXISTS usp_membresia_actualizar;
DROP PROCEDURE IF EXISTS usp_membresia_eliminar;
DROP PROCEDURE IF EXISTS usp_membresia_listar_activos;
DROP PROCEDURE IF EXISTS usp_membresia_listar_deuda;
DROP PROCEDURE IF EXISTS usp_membresia_eliminar_roles;
DROP PROCEDURE IF EXISTS usp_asesor_listar;
DROP PROCEDURE IF EXISTS usp_asesor_obtener;
DROP PROCEDURE IF EXISTS usp_asesor_insertar;
DROP PROCEDURE IF EXISTS usp_asesor_actualizar;
DROP PROCEDURE IF EXISTS usp_asesor_eliminar;

SELECT 'Renombre MEMBRESIA→MENSUALIDAD y ASESOR→TUTOR completado.' AS info;