/* ============================================================================
   PROYECTO ACADÉMICO - ESQUEMA COMPLETO (SQL Server)
   ----------------------------------------------------------------------------
   CONVENCIONES (aplican a TODO el proyecto):
     - IDs            : NVARCHAR(50)
     - Tablas/columnas: MAYÚSCULAS
     - FECHA          : CHAR(8)  formato DDMMYYYY   (ej. 15032000 = 15/03/2000)
     - HORA           : CHAR(8)  formato HH:MM:SS   (ej. 08:30:00)
     - Fecha y hora SIEMPRE en columnas separadas (mejor control).
     - Los CHECK validan el formato a nivel de base de datos.
   ============================================================================ */

/* ----------------------------------------------------------------------------
   0) LIMPIEZA (orden inverso de dependencias) - permite reejecutar el script
   ---------------------------------------------------------------------------- */
IF OBJECT_ID('dbo.usp_validate_user', 'P') IS NOT NULL DROP PROCEDURE dbo.usp_validate_user;
GO

DROP TABLE IF EXISTS NOTIFICACIONMEMBRESIA;
DROP TABLE IF EXISTS PAGOMEMBRESIA;
DROP TABLE IF EXISTS MEMBRESIA;
DROP TABLE IF EXISTS METODO_PAGO;
DROP TABLE IF EXISTS PROMOCIONES;
DROP TABLE IF EXISTS TURNO;
DROP TABLE IF EXISTS AULA;
DROP TABLE IF EXISTS PLAN;
DROP TABLE IF EXISTS LIBRO_ACCESO;
DROP TABLE IF EXISTS LIBRO_MATERIA;
DROP TABLE IF EXISTS LIBRO;
DROP TABLE IF EXISTS CUEST_RESPUESTA;
DROP TABLE IF EXISTS ALTERNATIVA_CUEST;
DROP TABLE IF EXISTS PREGUNTA_CUEST;
DROP TABLE IF EXISTS CUESTIONARIO;
DROP TABLE IF EXISTS ASISTENCIA;
DROP TABLE IF EXISTS ACTA_ASISTENCIA;
DROP TABLE IF EXISTS RESPUESTA_ALUMNO;
DROP TABLE IF EXISTS INTENTO_EXAMEN;
DROP TABLE IF EXISTS ALTERNATIVA;
DROP TABLE IF EXISTS PREGUNTA;
DROP TABLE IF EXISTS EXAMEN;
DROP TABLE IF EXISTS MATERIA;
DROP TABLE IF EXISTS USUARIO_MODULO;
DROP TABLE IF EXISTS GRUPO_MODULO;
DROP TABLE IF EXISTS TIPO_PERMISO;
DROP TABLE IF EXISTS SUBMODULO;
DROP TABLE IF EXISTS MODULO;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS TIPOUSUARIO;
GO

/* ============================================================================
   1) USUARIOS Y CONTROL DE ACCESO
   ============================================================================ */

CREATE TABLE TIPOUSUARIO (
    IDTIPOUSUARIO   NVARCHAR(50)    NOT NULL PRIMARY KEY,
    DESCRIPCION     NVARCHAR(255)   NOT NULL
);
GO

CREATE TABLE USUARIO (
    IDUSUARIO           NVARCHAR(50)    NOT NULL PRIMARY KEY,
    CONTRA              NVARCHAR(255)   NOT NULL,   -- guardar HASH, no texto plano
    NOMBRE              NVARCHAR(100)   NOT NULL,
    APELLIDO            NVARCHAR(100)   NOT NULL,
    DNI                 NVARCHAR(20)    NOT NULL UNIQUE,
    FECHANACIMIENTO     CHAR(8)         NULL CHECK (FECHANACIMIENTO LIKE '[0-3][0-9][0-1][0-9][0-9][0-9][0-9][0-9]'),
    DIRECCION           NVARCHAR(255)   NULL,
    ESTADO              NVARCHAR(50)    NOT NULL DEFAULT 'Activo',
    DISTRITO            NVARCHAR(100)   NULL,
    COLEGIO             NVARCHAR(150)   NULL,
    GRADO               NVARCHAR(50)    NULL,
    FECHAACTIVO         CHAR(8)         NULL CHECK (FECHAACTIVO LIKE '[0-3][0-9][0-1][0-9][0-9][0-9][0-9][0-9]'),
    EMAIL               NVARCHAR(150)   NOT NULL UNIQUE,
    TELPERSONAL         NVARCHAR(20)    NULL,
    TELAPODERADO        NVARCHAR(20)    NULL,
    SITUACIONACADEMICA  NVARCHAR(100)   NULL,
    IDTIPOUSUARIO       NVARCHAR(50)    NOT NULL
        FOREIGN KEY REFERENCES TIPOUSUARIO(IDTIPOUSUARIO)
);
GO
CREATE INDEX IX_USUARIO_TIPO ON USUARIO(IDTIPOUSUARIO);
GO

CREATE TABLE MODULO (
    IDMODULO            NVARCHAR(50)    NOT NULL PRIMARY KEY,
    NOMBRE              NVARCHAR(100)   NOT NULL,
    DESCRIPCION         NVARCHAR(255)   NULL,
    ICONO               NVARCHAR(100)   NULL,
    ORDEN               INT             NULL,
    ACTIVO              BIT             NOT NULL DEFAULT 1,
    FECHACREACION       CHAR(8)         NULL CHECK (FECHACREACION LIKE '[0-3][0-9][0-1][0-9][0-9][0-9][0-9][0-9]'),
    FECHAACTUALIZACION  CHAR(8)         NULL CHECK (FECHAACTUALIZACION LIKE '[0-3][0-9][0-1][0-9][0-9][0-9][0-9][0-9]')
);
GO

CREATE TABLE SUBMODULO (
    IDSUBMODULO     NVARCHAR(50)    NOT NULL PRIMARY KEY,
    NOMBRE          NVARCHAR(100)   NOT NULL,
    DESCRIPCION     NVARCHAR(255)   NULL,
    ICONO           NVARCHAR(100)   NULL,
    ORDEN           INT             NULL,
    ACTIVO          BIT             NOT NULL DEFAULT 1,
    IDMODULO        NVARCHAR(50)    NOT NULL
        FOREIGN KEY REFERENCES MODULO(IDMODULO)
);
GO
CREATE INDEX IX_SUBMODULO_MODULO ON SUBMODULO(IDMODULO);
GO

CREATE TABLE TIPO_PERMISO (
    IDTIPOPERMISO   NVARCHAR(50)    NOT NULL PRIMARY KEY,
    DESCRIPCION     NVARCHAR(255)   NOT NULL    -- ej. VER, CREAR, EDITAR, ELIMINAR
);
GO

-- Permisos por ROL (tipo de usuario) sobre un módulo
CREATE TABLE GRUPO_MODULO (
    IDGRUPOMODULO   NVARCHAR(50)    NOT NULL PRIMARY KEY,
    IDTIPOUSUARIO   NVARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES TIPOUSUARIO(IDTIPOUSUARIO),
    IDMODULO        NVARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES MODULO(IDMODULO),
    IDTIPOPERMISO   NVARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES TIPO_PERMISO(IDTIPOPERMISO),
    CONSTRAINT UQ_GRUPO_MODULO UNIQUE (IDTIPOUSUARIO, IDMODULO, IDTIPOPERMISO)
);
GO

-- Permisos específicos por USUARIO sobre un módulo (excepciones)
CREATE TABLE USUARIO_MODULO (
    IDUSUARIOMODULO NVARCHAR(50)    NOT NULL PRIMARY KEY,
    IDUSUARIO       NVARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES USUARIO(IDUSUARIO),
    IDMODULO        NVARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES MODULO(IDMODULO),
    IDTIPOPERMISO   NVARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES TIPO_PERMISO(IDTIPOPERMISO),
    CONSTRAINT UQ_USUARIO_MODULO UNIQUE (IDUSUARIO, IDMODULO, IDTIPOPERMISO)
);
GO

/* ============================================================================
   2) MATERIAS, EXÁMENES Y PREGUNTAS
   ============================================================================ */

CREATE TABLE MATERIA (
    IDMATERIA   NVARCHAR(50)    NOT NULL PRIMARY KEY,
    CODIGO      NVARCHAR(50)    NULL,
    NOMBRE      NVARCHAR(150)   NOT NULL
);
GO

CREATE TABLE EXAMEN (
    IDEXAMEN        NVARCHAR(50)    NOT NULL PRIMARY KEY,
    TITULO          NVARCHAR(200)   NOT NULL,
    DESCRIPCION     NVARCHAR(MAX)   NULL,
    TIPO            INT             NULL,   -- catálogo de tipos de examen (1,2,3...)
    DURACIONMIN     INT             NULL,
    PUNTAJETOTAL    DECIMAL(6,2)    NULL,
    PUNTAJEAPROBADO DECIMAL(6,2)    NULL,
    FECHAINICIO     CHAR(8)         NULL CHECK (FECHAINICIO LIKE '[0-3][0-9][0-1][0-9][0-9][0-9][0-9][0-9]'),
    FECHAFIN        CHAR(8)         NULL CHECK (FECHAFIN    LIKE '[0-3][0-9][0-1][0-9][0-9][0-9][0-9][0-9]'),
    HORAINICIO      CHAR(8)         NULL CHECK (HORAINICIO  LIKE '[0-2][0-9]:[0-5][0-9]:[0-5][0-9]'),
    HORAFIN         CHAR(8)         NULL CHECK (HORAFIN     LIKE '[0-2][0-9]:[0-5][0-9]:[0-5][0-9]'),
    TIEMPOLIMITE    CHAR(8)         NULL CHECK (TIEMPOLIMITE LIKE '[0-2][0-9]:[0-5][0-9]:[0-5][0-9]'),
    INTENTOSMAX     INT             NULL DEFAULT 1,
    VISIBLE         BIT             NOT NULL DEFAULT 1,
    IDUSUARIO       NVARCHAR(50)    NOT NULL
        FOREIGN KEY REFERENCES USUARIO(IDUSUARIO)   -- docente que lo crea
);
GO
CREATE INDEX IX_EXAMEN_USUARIO ON EXAMEN(IDUSUARIO);
GO

CREATE TABLE PREGUNTA (
    IDPREGUNTA      NVARCHAR(50)    NOT NULL PRIMARY KEY,
    TITULO          NVARCHAR(255)   NOT NULL,
    DESCRIPCION     NVARCHAR(MAX)   NULL,
    PUNTAJE         DECIMAL(6,2)    NULL,
    ORDEN           INT             NULL,
    IMAGEURL        NVARCHAR(255)   NULL,
    IDEXAMEN        NVARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES EXAMEN(IDEXAMEN),
    IDMATERIA       NVARCHAR(50)    NULL     FOREIGN KEY REFERENCES MATERIA(IDMATERIA)
);
GO
CREATE INDEX IX_PREGUNTA_EXAMEN  ON PREGUNTA(IDEXAMEN);
CREATE INDEX IX_PREGUNTA_MATERIA ON PREGUNTA(IDMATERIA);
GO

CREATE TABLE ALTERNATIVA (
    IDALTERNATIVA   NVARCHAR(50)    NOT NULL PRIMARY KEY,
    DESCRIPCION     NVARCHAR(MAX)   NOT NULL,
    ESCORRECTA      BIT             NOT NULL DEFAULT 0,
    ORDEN           INT             NULL,
    IMAGEURL        NVARCHAR(255)   NULL,
    IDPREGUNTA      NVARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES PREGUNTA(IDPREGUNTA)
);
GO
CREATE INDEX IX_ALTERNATIVA_PREGUNTA ON ALTERNATIVA(IDPREGUNTA);
GO

CREATE TABLE INTENTO_EXAMEN (
    IDINTENTOEXAMEN NVARCHAR(50)    NOT NULL PRIMARY KEY,
    NUMEROINTENTO   INT             NOT NULL DEFAULT 1,
    FECHAINICIO     CHAR(8)         NULL CHECK (FECHAINICIO LIKE '[0-3][0-9][0-1][0-9][0-9][0-9][0-9][0-9]'),
    HORAINICIO      CHAR(8)         NULL CHECK (HORAINICIO  LIKE '[0-2][0-9]:[0-5][0-9]:[0-5][0-9]'),
    FECHAFIN        CHAR(8)         NULL CHECK (FECHAFIN    LIKE '[0-3][0-9][0-1][0-9][0-9][0-9][0-9][0-9]'),
    HORAFIN         CHAR(8)         NULL CHECK (HORAFIN     LIKE '[0-2][0-9]:[0-5][0-9]:[0-5][0-9]'),
    PUNTAJEOBTENIDO DECIMAL(6,2)    NULL,
    CANTCORRECTAS   INT             NULL DEFAULT 0,
    CANTINCORRECTAS INT             NULL DEFAULT 0,
    CANTSINRESPONDER INT            NULL DEFAULT 0,
    ESTADO          INT             NULL,       -- ej. 0=en curso, 1=finalizado
    APROBADO        BIT             NULL,
    IDEXAMEN        NVARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES EXAMEN(IDEXAMEN),
    IDUSUARIO       NVARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES USUARIO(IDUSUARIO)
);
GO
CREATE INDEX IX_INTENTO_EXAMEN_EXAMEN  ON INTENTO_EXAMEN(IDEXAMEN);
CREATE INDEX IX_INTENTO_EXAMEN_USUARIO ON INTENTO_EXAMEN(IDUSUARIO);
GO

CREATE TABLE RESPUESTA_ALUMNO (
    IDRESPUESTAALUMNO NVARCHAR(50)  NOT NULL PRIMARY KEY,
    PUNTAJEOBTENIDO   DECIMAL(6,2)  NULL,
    RESPABIERTA       NVARCHAR(MAX) NULL,       -- para preguntas abiertas
    IDINTENTOEXAMEN   NVARCHAR(50)  NOT NULL FOREIGN KEY REFERENCES INTENTO_EXAMEN(IDINTENTOEXAMEN),
    IDPREGUNTA        NVARCHAR(50)  NOT NULL FOREIGN KEY REFERENCES PREGUNTA(IDPREGUNTA),
    IDALTERNATIVA     NVARCHAR(50)  NULL     FOREIGN KEY REFERENCES ALTERNATIVA(IDALTERNATIVA)
);
GO
CREATE INDEX IX_RESP_ALUMNO_INTENTO ON RESPUESTA_ALUMNO(IDINTENTOEXAMEN);
CREATE INDEX IX_RESP_ALUMNO_PREGUNTA ON RESPUESTA_ALUMNO(IDPREGUNTA);
GO

/* ============================================================================
   3) ASISTENCIA
   ============================================================================ */

CREATE TABLE ACTA_ASISTENCIA (
    IDACTAASISTENCIA NVARCHAR(50)   NOT NULL PRIMARY KEY,
    FECHAINICIO      CHAR(8)        NULL CHECK (FECHAINICIO LIKE '[0-3][0-9][0-1][0-9][0-9][0-9][0-9][0-9]'),
    HORAINICIO       CHAR(8)        NULL CHECK (HORAINICIO  LIKE '[0-2][0-9]:[0-5][0-9]:[0-5][0-9]'),
    FECHAFINAL       CHAR(8)        NULL CHECK (FECHAFINAL  LIKE '[0-3][0-9][0-1][0-9][0-9][0-9][0-9][0-9]'),
    HORAFINAL        CHAR(8)        NULL CHECK (HORAFINAL   LIKE '[0-2][0-9]:[0-5][0-9]:[0-5][0-9]')
);
GO

CREATE TABLE ASISTENCIA (
    IDASISTENCIA     NVARCHAR(50)   NOT NULL PRIMARY KEY,
    FECHAREGISTRO    CHAR(8)        NULL CHECK (FECHAREGISTRO LIKE '[0-3][0-9][0-1][0-9][0-9][0-9][0-9][0-9]'),
    HORAINICIO       CHAR(8)        NULL CHECK (HORAINICIO    LIKE '[0-2][0-9]:[0-5][0-9]:[0-5][0-9]'),
    FECHAFINAL       CHAR(8)        NULL CHECK (FECHAFINAL    LIKE '[0-3][0-9][0-1][0-9][0-9][0-9][0-9][0-9]'),
    HORAFINAL        CHAR(8)        NULL CHECK (HORAFINAL     LIKE '[0-2][0-9]:[0-5][0-9]:[0-5][0-9]'),
    ESTADO           NVARCHAR(50)   NULL,       -- ej. Presente, Tarde, Ausente
    JUSTIFICADO      BIT            NOT NULL DEFAULT 0,
    IDUSUARIO        NVARCHAR(50)   NOT NULL FOREIGN KEY REFERENCES USUARIO(IDUSUARIO),
    IDACTAASISTENCIA NVARCHAR(50)   NULL     FOREIGN KEY REFERENCES ACTA_ASISTENCIA(IDACTAASISTENCIA)
);
GO
CREATE INDEX IX_ASISTENCIA_USUARIO ON ASISTENCIA(IDUSUARIO);
CREATE INDEX IX_ASISTENCIA_ACTA    ON ASISTENCIA(IDACTAASISTENCIA);
GO

/* ============================================================================
   4) CUESTIONARIOS (flujo independiente del examen)
   ============================================================================ */

CREATE TABLE CUESTIONARIO (
    IDCUESTIONARIO     NVARCHAR(50)  NOT NULL PRIMARY KEY,
    TITULO             NVARCHAR(200) NOT NULL,
    DESCRIPCION        NVARCHAR(MAX) NULL,
    FECHAINICIO        CHAR(8)       NULL CHECK (FECHAINICIO LIKE '[0-3][0-9][0-1][0-9][0-9][0-9][0-9][0-9]'),
    HORAINICIO         CHAR(8)       NULL CHECK (HORAINICIO  LIKE '[0-2][0-9]:[0-5][0-9]:[0-5][0-9]'),
    FECHAFINAL         CHAR(8)       NULL CHECK (FECHAFINAL  LIKE '[0-3][0-9][0-1][0-9][0-9][0-9][0-9][0-9]'),
    HORAFINAL          CHAR(8)       NULL CHECK (HORAFINAL   LIKE '[0-2][0-9]:[0-5][0-9]:[0-5][0-9]'),
    ACTIVO             BIT           NOT NULL DEFAULT 1,
    ENLACECUESTIONARIO NVARCHAR(255) NULL
);
GO

CREATE TABLE PREGUNTA_CUEST (
    IDPREGUNTACUEST NVARCHAR(50)    NOT NULL PRIMARY KEY,
    TITULO          NVARCHAR(255)   NOT NULL,
    DESCRIPCION     NVARCHAR(MAX)   NULL,
    IDCUESTIONARIO  NVARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES CUESTIONARIO(IDCUESTIONARIO)
);
GO
CREATE INDEX IX_PREGUNTA_CUEST ON PREGUNTA_CUEST(IDCUESTIONARIO);
GO

CREATE TABLE ALTERNATIVA_CUEST (
    IDALTERNATIVACUEST NVARCHAR(50) NOT NULL PRIMARY KEY,
    DESCRIPCION        NVARCHAR(MAX) NOT NULL,
    IDPREGUNTACUEST    NVARCHAR(50) NOT NULL FOREIGN KEY REFERENCES PREGUNTA_CUEST(IDPREGUNTACUEST)
);
GO
CREATE INDEX IX_ALT_CUEST_PREGUNTA ON ALTERNATIVA_CUEST(IDPREGUNTACUEST);
GO

CREATE TABLE CUEST_RESPUESTA (
    IDCUESTRESPUESTA   NVARCHAR(50) NOT NULL PRIMARY KEY,
    FECHAREGISTRO      CHAR(8)      NULL CHECK (FECHAREGISTRO LIKE '[0-3][0-9][0-1][0-9][0-9][0-9][0-9][0-9]'),
    HORAREGISTRO       CHAR(8)      NULL CHECK (HORAREGISTRO  LIKE '[0-2][0-9]:[0-5][0-9]:[0-5][0-9]'),
    IDCUESTIONARIO     NVARCHAR(50) NOT NULL FOREIGN KEY REFERENCES CUESTIONARIO(IDCUESTIONARIO),
    IDALTERNATIVACUEST NVARCHAR(50) NOT NULL FOREIGN KEY REFERENCES ALTERNATIVA_CUEST(IDALTERNATIVACUEST)
);
GO
CREATE INDEX IX_CUEST_RESP_CUEST ON CUEST_RESPUESTA(IDCUESTIONARIO);
CREATE INDEX IX_CUEST_RESP_ALT   ON CUEST_RESPUESTA(IDALTERNATIVACUEST);
GO

/* ============================================================================
   5) BIBLIOTECA
   ============================================================================ */

CREATE TABLE LIBRO (
    IDLIBRO        NVARCHAR(50)     NOT NULL PRIMARY KEY,
    TITULO         NVARCHAR(200)    NOT NULL,
    DESCRIPCION    NVARCHAR(MAX)    NULL,
    AUTOR          NVARCHAR(150)    NULL,
    ANIOPUBLICACION NVARCHAR(4)     NULL,
    URLCONTENIDO   NVARCHAR(255)    NULL,
    IMGPORTADA     NVARCHAR(255)    NULL,
    ESTADO         NVARCHAR(50)     NULL DEFAULT 'Activo'
);
GO

-- Relación N:M  (un libro puede pertenecer a varias materias)
CREATE TABLE LIBRO_MATERIA (
    IDLIBROMATERIA NVARCHAR(50)     NOT NULL PRIMARY KEY,
    IDLIBRO        NVARCHAR(50)     NOT NULL FOREIGN KEY REFERENCES LIBRO(IDLIBRO),
    IDMATERIA      NVARCHAR(50)     NOT NULL FOREIGN KEY REFERENCES MATERIA(IDMATERIA),
    CONSTRAINT UQ_LIBRO_MATERIA UNIQUE (IDLIBRO, IDMATERIA)
);
GO

CREATE TABLE LIBRO_ACCESO (
    IDLIBROACCESO  NVARCHAR(50)     NOT NULL PRIMARY KEY,
    FECHAINGRESO   CHAR(8)          NULL CHECK (FECHAINGRESO LIKE '[0-3][0-9][0-1][0-9][0-9][0-9][0-9][0-9]'),
    HORAINGRESO    CHAR(8)          NULL CHECK (HORAINGRESO  LIKE '[0-2][0-9]:[0-5][0-9]:[0-5][0-9]'),
    IDUSUARIO      NVARCHAR(50)     NOT NULL FOREIGN KEY REFERENCES USUARIO(IDUSUARIO),
    IDLIBRO        NVARCHAR(50)     NOT NULL FOREIGN KEY REFERENCES LIBRO(IDLIBRO)
);
GO
CREATE INDEX IX_LIBRO_ACCESO_USUARIO ON LIBRO_ACCESO(IDUSUARIO);
CREATE INDEX IX_LIBRO_ACCESO_LIBRO   ON LIBRO_ACCESO(IDLIBRO);
GO

/* ============================================================================
   6) MEMBRESÍAS, PAGOS Y CATÁLOGOS
   ============================================================================ */

CREATE TABLE PLAN (
    IDPLAN       NVARCHAR(50)   NOT NULL PRIMARY KEY,
    NOMBRE       NVARCHAR(100)  NOT NULL,
    DESCRIPCION  NVARCHAR(255)  NULL,
    DURACIONDIAS INT            NULL,
    PRECIO       DECIMAL(10,2)  NULL,
    ACTIVO       BIT            NOT NULL DEFAULT 1
);
GO

CREATE TABLE AULA (
    IDAULA             NVARCHAR(50)   NOT NULL PRIMARY KEY,
    NOMBRE             NVARCHAR(100)  NOT NULL,
    DESCRIPCION        NVARCHAR(MAX)  NULL,
    CAPACIDAD          INT            NULL,
    ACTIVO             BIT            NOT NULL DEFAULT 1,
    ENLACEVIRTUAL      NVARCHAR(255)  NULL,
    ENLACECUESTIONARIO NVARCHAR(255)  NULL
);
GO

CREATE TABLE TURNO (
    IDTURNO     NVARCHAR(50)   NOT NULL PRIMARY KEY,
    DESCRIPCION NVARCHAR(100)  NOT NULL   -- ej. Mañana, Tarde, Noche
);
GO

CREATE TABLE PROMOCIONES (
    IDPROMOCION NVARCHAR(50)   NOT NULL PRIMARY KEY,
    TITULO      NVARCHAR(150)  NOT NULL,
    DESCRIPCION NVARCHAR(255)  NULL,
    DESCUENTO   INT            NULL       -- porcentaje
);
GO

CREATE TABLE METODO_PAGO (
    IDMETODOPAGO NVARCHAR(50)  NOT NULL PRIMARY KEY,
    TITULO       NVARCHAR(100) NOT NULL,
    DESCRIPCION  NVARCHAR(255) NULL,
    ACTIVO       BIT           NOT NULL DEFAULT 1
);
GO

CREATE TABLE MEMBRESIA (
    IDMEMBRESIA    NVARCHAR(50)  NOT NULL PRIMARY KEY,
    FECHAINICIO    CHAR(8)       NULL CHECK (FECHAINICIO  LIKE '[0-3][0-9][0-1][0-9][0-9][0-9][0-9][0-9]'),
    FECHAFIN       CHAR(8)       NULL CHECK (FECHAFIN     LIKE '[0-3][0-9][0-1][0-9][0-9][0-9][0-9][0-9]'),
    ESTADOMIEMBRO  INT           NULL,
    CICLO          INT           NULL,
    MONTOTOTAL     DECIMAL(10,2) NULL,
    OBSERVACIONES  NVARCHAR(MAX) NULL,
    FECHAREGISTRO  CHAR(8)       NULL CHECK (FECHAREGISTRO LIKE '[0-3][0-9][0-1][0-9][0-9][0-9][0-9][0-9]'),
    HORAREGISTRO   CHAR(8)       NULL CHECK (HORAREGISTRO  LIKE '[0-2][0-9]:[0-5][0-9]:[0-5][0-9]'),
    FECHAPAGO      CHAR(8)       NULL CHECK (FECHAPAGO     LIKE '[0-3][0-9][0-1][0-9][0-9][0-9][0-9][0-9]'),
    IDPLAN         NVARCHAR(50)  NOT NULL FOREIGN KEY REFERENCES PLAN(IDPLAN),
    IDAULA         NVARCHAR(50)  NULL     FOREIGN KEY REFERENCES AULA(IDAULA),
    IDTURNO        NVARCHAR(50)  NULL     FOREIGN KEY REFERENCES TURNO(IDTURNO),
    IDPROMOCION    NVARCHAR(50)  NULL     FOREIGN KEY REFERENCES PROMOCIONES(IDPROMOCION),
    IDUSUARIO      NVARCHAR(50)  NOT NULL FOREIGN KEY REFERENCES USUARIO(IDUSUARIO),   -- titular
    REGISTRADOPOR  NVARCHAR(50)  NULL     FOREIGN KEY REFERENCES USUARIO(IDUSUARIO)    -- quien registra
);
GO
CREATE INDEX IX_MEMBRESIA_USUARIO ON MEMBRESIA(IDUSUARIO);
CREATE INDEX IX_MEMBRESIA_PLAN    ON MEMBRESIA(IDPLAN);
GO

CREATE TABLE PAGOMEMBRESIA (
    IDPAGOMEMBRESIA NVARCHAR(50)  NOT NULL PRIMARY KEY,
    MONTO           DECIMAL(10,2) NOT NULL,
    COMPROBANTEURL  NVARCHAR(255) NULL,
    FECHAPAGO       CHAR(8)       NULL CHECK (FECHAPAGO LIKE '[0-3][0-9][0-1][0-9][0-9][0-9][0-9][0-9]'),
    HORAPAGO        CHAR(8)       NULL CHECK (HORAPAGO  LIKE '[0-2][0-9]:[0-5][0-9]:[0-5][0-9]'),
    OBSERVACIONES   NVARCHAR(MAX) NULL,
    IDMEMBRESIA     NVARCHAR(50)  NOT NULL FOREIGN KEY REFERENCES MEMBRESIA(IDMEMBRESIA),
    IDMETODOPAGO    NVARCHAR(50)  NOT NULL FOREIGN KEY REFERENCES METODO_PAGO(IDMETODOPAGO),
    IDUSUARIO       NVARCHAR(50)  NULL     FOREIGN KEY REFERENCES USUARIO(IDUSUARIO)   -- quien registra el pago
);
GO
CREATE INDEX IX_PAGOMEMBRESIA_MEMBRESIA ON PAGOMEMBRESIA(IDMEMBRESIA);
GO

CREATE TABLE NOTIFICACIONMEMBRESIA (
    IDNOTIFICACIONMEMBRESIA NVARCHAR(50) NOT NULL PRIMARY KEY,
    TIPO          NVARCHAR(20)  NULL,
    MENSAJE       NVARCHAR(MAX) NULL,
    FECHACREACION CHAR(8)       NULL CHECK (FECHACREACION LIKE '[0-3][0-9][0-1][0-9][0-9][0-9][0-9][0-9]'),
    HORACREACION  CHAR(8)       NULL CHECK (HORACREACION  LIKE '[0-2][0-9]:[0-5][0-9]:[0-5][0-9]'),
    FECHALIMITE   CHAR(8)       NULL CHECK (FECHALIMITE   LIKE '[0-3][0-9][0-1][0-9][0-9][0-9][0-9][0-9]'),
    ACTIVA        BIT           NOT NULL DEFAULT 1,
    IDMEMBRESIA   NVARCHAR(50)  NOT NULL FOREIGN KEY REFERENCES MEMBRESIA(IDMEMBRESIA),
    IDUSUARIO     NVARCHAR(50)  NOT NULL FOREIGN KEY REFERENCES USUARIO(IDUSUARIO)
);
GO
CREATE INDEX IX_NOTIF_MEMBRESIA ON NOTIFICACIONMEMBRESIA(IDMEMBRESIA);
CREATE INDEX IX_NOTIF_USUARIO   ON NOTIFICACIONMEMBRESIA(IDUSUARIO);
GO

/* ============================================================================
   7) DATOS INICIALES (SEED)
   ============================================================================ */

INSERT INTO TIPOUSUARIO (IDTIPOUSUARIO, DESCRIPCION) VALUES
('1', 'Estudiante'),
('2', 'Docente'),
('3', 'Administrador');
GO

INSERT INTO USUARIO
(IDUSUARIO, CONTRA, NOMBRE, APELLIDO, DNI, FECHANACIMIENTO, DIRECCION, ESTADO, DISTRITO, COLEGIO, GRADO, FECHAACTIVO, EMAIL, TELPERSONAL, TELAPODERADO, SITUACIONACADEMICA, IDTIPOUSUARIO)
VALUES
('1', '1234', 'Carlos', 'Ramirez', '12345678', '15032000', 'Av. Lima 123',      'Activo', 'Miraflores', 'Colegio San Jose', '5to', '01012024', 'carlos@gmail.com', '987654321', '912345678', 'Regular', '1'),
('2', '1234', 'Maria',  'Lopez',   '87654321', '20071990', 'Jr. Cusco 456',     'Activo', 'San Isidro', NULL,               NULL,  '01012024', 'maria@gmail.com',  '998877665', NULL,        NULL,      '2'),
('3', '1234', 'Pedro',  'Torres',  '11223344', '10111985', 'Calle Arequipa 789','Activo', 'Surco',      NULL,               NULL,  '01012024', 'pedro@gmail.com',  '977665544', NULL,        NULL,      '3');
GO

/* ============================================================================
   8) STORED PROCEDURE DE VALIDACIÓN
   ----------------------------------------------------------------------------
   NOTA: la contraseña se compara en texto plano (igual que tu versión actual).
   Para producción se recomienda guardar y comparar un HASH.
   ============================================================================ */

CREATE PROCEDURE dbo.usp_validate_user
    @username NVARCHAR(50),
    @password NVARCHAR(255)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @IDTIPOUSUARIO NVARCHAR(50);

    SELECT @IDTIPOUSUARIO = IDTIPOUSUARIO
    FROM USUARIO
    WHERE IDUSUARIO = @username
      AND CONTRA    = @password
      AND ESTADO    = 'Activo';

    IF @IDTIPOUSUARIO IS NOT NULL
    BEGIN
        SELECT
            CAST(1 AS BIT) AS is_valid,
            CASE @IDTIPOUSUARIO
                WHEN '1' THEN 'estudiante'
                WHEN '2' THEN 'docente'
                WHEN '3' THEN 'administrador'
                ELSE 'estudiante'
            END AS role;
    END
    ELSE
    BEGIN
        SELECT
            CAST(0 AS BIT) AS is_valid,
            'estudiante' AS role;
    END
END;
GO
