-- Convertido automáticamente desde db_scripts/modulos_structure.sql
-- MySQL 8 — Academia 3.0

USE `AcademiaDB`;

-- ========================================
-- SCRIPT: Creación de Tablas de Módulos
-- Fecha: 2026-05-09
-- Descripción: Tablas para gestión escalable de acceso a módulos
-- ========================================

-- 1. Tabla de Módulos (Módulos principales)
IF OBJECT_ID('MODULO', 'U') IS NOT NULL 
    DROP TABLE MODULO;

CREATE TABLE IF NOT EXISTS MODULO (
    IDMODULO            VARCHAR(50)    PRIMARY KEY,
    NOMBRE              VARCHAR(150)   NOT NULL UNIQUE,
    DESCRIPCION         VARCHAR(500),
    ICONO               VARCHAR(100),  -- Nombre del ícono (FontAwesome, etc.)
    ORDEN               INT             DEFAULT 0,
    ACTIVO              TINYINT(1)             DEFAULT 1,
    FECHA_CREACION      VARCHAR(20)    DEFAULT CONVERT(VARCHAR(8), NOW(), 112) + ' ' + CONVERT(VARCHAR(8), NOW(), 108),
    FECHA_ACTUALIZACION VARCHAR(20)    DEFAULT CONVERT(VARCHAR(8), NOW(), 112) + ' ' + CONVERT(VARCHAR(8), NOW(), 108)
);

-- 2. Tabla de Submódulos
IF OBJECT_ID('SUBMODULO', 'U') IS NOT NULL 
    DROP TABLE SUBMODULO;

CREATE TABLE IF NOT EXISTS SUBMODULO (
    IDSUBMODULO         VARCHAR(50)    PRIMARY KEY,
    IDMODULO VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDMODULO) REFERENCES MODULO(IDMODULO),
    NOMBRE              VARCHAR(150)   NOT NULL,
    DESCRIPCION         VARCHAR(500),
    ICONO               VARCHAR(100),
    ORDEN               INT             DEFAULT 0,
    ACTIVO              TINYINT(1)             DEFAULT 1,
    FECHA_CREACION      VARCHAR(20)    DEFAULT CONVERT(VARCHAR(8), NOW(), 112) + ' ' + CONVERT(VARCHAR(8), NOW(), 108),
    FECHA_ACTUALIZACION VARCHAR(20)    DEFAULT CONVERT(VARCHAR(8), NOW(), 112) + ' ' + CONVERT(VARCHAR(8), NOW(), 108)
);

-- 3. Tabla de Permisos (Tipos de acceso escalables)
IF OBJECT_ID('TIPO_PERMISO', 'U') IS NOT NULL 
    DROP TABLE TIPO_PERMISO;

CREATE TABLE IF NOT EXISTS TIPO_PERMISO (
    IDPERMISO           VARCHAR(50)    PRIMARY KEY,
    NOMBRE              VARCHAR(100)   NOT NULL UNIQUE,
    DESCRIPCION         VARCHAR(255),
    FECHA_CREACION      VARCHAR(20)    DEFAULT CONVERT(VARCHAR(8), NOW(), 112) + ' ' + CONVERT(VARCHAR(8), NOW(), 108)
);

-- 4. Tabla de Asignación de Módulos a Usuarios (Principal)
IF OBJECT_ID('USUARIO_MODULO', 'U') IS NOT NULL 
    DROP TABLE USUARIO_MODULO;

CREATE TABLE IF NOT EXISTS USUARIO_MODULO (
    IDUSUARIO_MODULO    VARCHAR(50)    PRIMARY KEY,
    IDUSUARIO VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
    IDMODULO VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDMODULO) REFERENCES MODULO(IDMODULO),
    PERMISOS            LONGTEXT,  -- JSON: ['read', 'write', 'delete', 'admin']
    FECHA_ASIGNACION    VARCHAR(20)    DEFAULT CONVERT(VARCHAR(8), NOW(), 112) + ' ' + CONVERT(VARCHAR(8), NOW(), 108),
    FECHA_ACTUALIZACION VARCHAR(20)    DEFAULT CONVERT(VARCHAR(8), NOW(), 112) + ' ' + CONVERT(VARCHAR(8), NOW(), 108),
    ASIGNADO_POR        VARCHAR(50),   -- Usuario que asignó el permiso
    ACTIVO              TINYINT(1)             DEFAULT 1,
    UNIQUE (IDUSUARIO, IDMODULO)
);

-- 5. Tabla de Asignación de Módulos a Roles/Grupos
IF OBJECT_ID('GRUPO_MODULO', 'U') IS NOT NULL 
    DROP TABLE GRUPO_MODULO;

CREATE TABLE IF NOT EXISTS GRUPO_MODULO (
    IDGRUPO_MODULO      VARCHAR(50)    PRIMARY KEY,
    IDGRUPO VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDGRUPO) REFERENCES TIPOUSUARIO(IDTIPOUSUARIO), -- Referencia a tipo de usuario (admin, secretario, etc.)
    IDMODULO VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDMODULO) REFERENCES MODULO(IDMODULO),
    PERMISOS            LONGTEXT,  -- JSON: ['read', 'write', 'delete', 'admin']
    FECHA_ASIGNACION    VARCHAR(20)    DEFAULT CONVERT(VARCHAR(8), NOW(), 112) + ' ' + CONVERT(VARCHAR(8), NOW(), 108),
    FECHA_ACTUALIZACION VARCHAR(20)    DEFAULT CONVERT(VARCHAR(8), NOW(), 112) + ' ' + CONVERT(VARCHAR(8), NOW(), 108),
    ACTIVO              TINYINT(1)             DEFAULT 1,
    UNIQUE (IDGRUPO, IDMODULO)
);

-- Crear índices para mejorar rendimiento
CREATE INDEX IDX_SUBMODULO_MODULO ON SUBMODULO(IDMODULO);
CREATE INDEX IDX_USUARIO_MODULO_USUARIO ON USUARIO_MODULO(IDUSUARIO);
CREATE INDEX IDX_USUARIO_MODULO_MODULO ON USUARIO_MODULO(IDMODULO);
CREATE INDEX IDX_GRUPO_MODULO_GRUPO ON GRUPO_MODULO(IDGRUPO);
CREATE INDEX IDX_GRUPO_MODULO_MODULO ON GRUPO_MODULO(IDMODULO);

SELECT 'Tablas de módulos creadas exitosamente';
