/* ============================================================================
   CATEGORIA (exámenes) + FK en MATERIA
   Fecha: 16/07/2026
   ============================================================================ */

IF OBJECT_ID('dbo.CATEGORIA', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.CATEGORIA (
        IDCATEGORIA NVARCHAR(50)   NOT NULL PRIMARY KEY,
        NOMBRE      NVARCHAR(100)  NOT NULL,
        PORCENTAJE  DECIMAL(5,2)   NULL,
        ORDEN       INT            NOT NULL CONSTRAINT DF_CATEGORIA_ORDEN DEFAULT (0),
        ACTIVO      BIT            NOT NULL CONSTRAINT DF_CATEGORIA_ACTIVO DEFAULT (1)
    );
    PRINT 'Tabla CATEGORIA creada.';
END
ELSE
    PRINT 'Tabla CATEGORIA ya existe.';
GO

IF NOT EXISTS (SELECT 1 FROM dbo.CATEGORIA WHERE IDCATEGORIA = 'CAT001')
    INSERT INTO dbo.CATEGORIA (IDCATEGORIA, NOMBRE, PORCENTAJE, ORDEN, ACTIVO)
    VALUES ('CAT001', 'Habilidades', 20.0, 1, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.CATEGORIA WHERE IDCATEGORIA = 'CAT002')
    INSERT INTO dbo.CATEGORIA (IDCATEGORIA, NOMBRE, PORCENTAJE, ORDEN, ACTIVO)
    VALUES ('CAT002', 'Matematica', 20.0, 2, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.CATEGORIA WHERE IDCATEGORIA = 'CAT003')
    INSERT INTO dbo.CATEGORIA (IDCATEGORIA, NOMBRE, PORCENTAJE, ORDEN, ACTIVO)
    VALUES ('CAT003', 'Humanidades', 40.0, 3, 1);
IF NOT EXISTS (SELECT 1 FROM dbo.CATEGORIA WHERE IDCATEGORIA = 'CAT004')
    INSERT INTO dbo.CATEGORIA (IDCATEGORIA, NOMBRE, PORCENTAJE, ORDEN, ACTIVO)
    VALUES ('CAT004', 'Ciencias', 20.0, 4, 1);
GO

IF COL_LENGTH('MATERIA', 'IDCATEGORIA') IS NULL
BEGIN
    ALTER TABLE dbo.MATERIA ADD IDCATEGORIA NVARCHAR(50) NULL;
    PRINT 'Columna MATERIA.IDCATEGORIA agregada.';
END
ELSE
    PRINT 'Columna MATERIA.IDCATEGORIA ya existe.';
GO

IF COL_LENGTH('MATERIA', 'ACTIVO') IS NULL
BEGIN
    ALTER TABLE dbo.MATERIA ADD ACTIVO BIT NOT NULL CONSTRAINT DF_MATERIA_ACTIVO DEFAULT (1);
    PRINT 'Columna MATERIA.ACTIVO agregada.';
END
ELSE
    PRINT 'Columna MATERIA.ACTIVO ya existe.';
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_MATERIA_CATEGORIA'
)
BEGIN
    ALTER TABLE dbo.MATERIA
        ADD CONSTRAINT FK_MATERIA_CATEGORIA
        FOREIGN KEY (IDCATEGORIA) REFERENCES dbo.CATEGORIA(IDCATEGORIA);
    PRINT 'FK_MATERIA_CATEGORIA creada.';
END
ELSE
    PRINT 'FK_MATERIA_CATEGORIA ya existe.';
GO

PRINT 'CATEGORIA y vínculo en MATERIA listos.';
GO
