-- ============================================================================
-- EXAMEN: TODASLASULA + EXAMEN_AULA + plantilla distribución — MySQL 8
-- Fecha: 17/07/2026
-- ============================================================================

USE `AcademiaDB`;

SET @col_EXAMEN_TODASLASULA := (
    SELECT COUNT(*) FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'EXAMEN' AND COLUMN_NAME = 'TODASLASULA'
);
SET @sql_EXAMEN_TODASLASULA := IF(
    @col_EXAMEN_TODASLASULA = 0,
    'ALTER TABLE EXAMEN ADD TODASLASULA TINYINT(1) NOT NULL DEFAULT 1',
    'SELECT 1'
);
PREPARE stmt FROM @sql_EXAMEN_TODASLASULA;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

CREATE TABLE IF NOT EXISTS EXAMEN_AULA (
    IDEXAMENAULA VARCHAR(50) NOT NULL PRIMARY KEY,
    IDEXAMEN     VARCHAR(50) NOT NULL,
    IDAULA       VARCHAR(50) NOT NULL,
    CONSTRAINT UQ_EXAMEN_AULA UNIQUE (IDEXAMEN, IDAULA),
    CONSTRAINT FK_EXAMEN_AULA_EXAMEN FOREIGN KEY (IDEXAMEN) REFERENCES EXAMEN(IDEXAMEN),
    CONSTRAINT FK_EXAMEN_AULA_AULA   FOREIGN KEY (IDAULA) REFERENCES AULA(IDAULA)
);

CREATE INDEX IX_EXAMEN_AULA_EXAMEN ON EXAMEN_AULA(IDEXAMEN);
CREATE INDEX IX_EXAMEN_AULA_AULA   ON EXAMEN_AULA(IDAULA);

CREATE TABLE IF NOT EXISTS EXAMEN_PLANTILLA (
    IDPLANTILLA   INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    TIPO          INT NOT NULL,
    CODIGOMATERIA VARCHAR(50) NOT NULL,
    CANTIDAD      INT NOT NULL
);

DELETE FROM EXAMEN_PLANTILLA;

INSERT INTO EXAMEN_PLANTILLA (TIPO, CODIGOMATERIA, CANTIDAD) VALUES
(40, 'HM', 4), (40, 'HV', 4),
(40, 'ARIT', 2), (40, 'GEO', 2), (40, 'ALGE', 2), (40, 'TRIGO', 2),
(40, 'LENGUA', 2), (40, 'PSI', 2), (40, 'CIV', 2), (40, 'HP', 2),
(40, 'HU', 2), (40, 'GEO_L', 2), (40, 'ECO', 2), (40, 'FILO', 2),
(40, 'FIS', 2), (40, 'QUI', 2), (40, 'BIO', 4);

INSERT INTO EXAMEN_PLANTILLA (TIPO, CODIGOMATERIA, CANTIDAD) VALUES
(100, 'HM', 10), (100, 'HV', 10),
(100, 'ARIT', 5), (100, 'GEO', 5), (100, 'ALGE', 5), (100, 'TRIGO', 5),
(100, 'LENGUA', 5), (100, 'PSI', 5), (100, 'CIV', 5), (100, 'HP', 5),
(100, 'HU', 5), (100, 'GEO_L', 5), (100, 'ECO', 5), (100, 'FILO', 5),
(100, 'FIS', 5), (100, 'QUI', 5), (100, 'BIO', 10);
