-- Convertido automáticamente desde db_scripts/16_07_2026/13.categoria_materia_tablas.sql
-- MySQL 8 — Academia 3.0

USE `AcademiaDB`;

/* ============================================================================
   CATEGORIA (exámenes) + FK en MATERIA
   Fecha: 16/07/2026
   ============================================================================ */

-- create if missing CATEGORIA
    CREATE TABLE IF NOT EXISTS CATEGORIA (
        IDCATEGORIA VARCHAR(50)   NOT NULL PRIMARY KEY,
        NOMBRE      VARCHAR(100)  NOT NULL,
        PORCENTAJE  DECIMAL(5,2)   NULL,
        ORDEN       INT            NOT NULL CONSTRAINT DF_CATEGORIA_ORDEN DEFAULT (0),
        ACTIVO      TINYINT(1)            NOT NULL DEFAULT 1
    );
    SELECT 'Tabla CATEGORIA creada.';

INSERT IGNORE INTO CATEGORIA (IDCATEGORIA, NOMBRE, PORCENTAJE, ORDEN, ACTIVO)
    VALUES ('CAT001', 'Habilidades', 20.0, 1, 1);
INSERT IGNORE INTO CATEGORIA (IDCATEGORIA, NOMBRE, PORCENTAJE, ORDEN, ACTIVO)
    VALUES ('CAT002', 'Matematica', 20.0, 2, 1);
INSERT IGNORE INTO CATEGORIA (IDCATEGORIA, NOMBRE, PORCENTAJE, ORDEN, ACTIVO)
    VALUES ('CAT003', 'Humanidades', 40.0, 3, 1);
INSERT IGNORE INTO CATEGORIA (IDCATEGORIA, NOMBRE, PORCENTAJE, ORDEN, ACTIVO)
    VALUES ('CAT004', 'Ciencias', 20.0, 4, 1);

SET @col_MATERIA_IDCATEGORIA := (
    SELECT COUNT(*) FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'MATERIA' AND COLUMN_NAME = 'IDCATEGORIA'
);
SET @sql_MATERIA_IDCATEGORIA := IF(@col_MATERIA_IDCATEGORIA = 0, 'ALTER TABLE MATERIA ADD IDCATEGORIA VARCHAR(50) NULL', 'SELECT 1');
PREPARE stmt FROM @sql_MATERIA_IDCATEGORIA; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @col_MATERIA_ACTIVO := (
    SELECT COUNT(*) FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'MATERIA' AND COLUMN_NAME = 'ACTIVO'
);
SET @sql_MATERIA_ACTIVO := IF(@col_MATERIA_ACTIVO = 0, 'ALTER TABLE MATERIA ADD ACTIVO TINYINT(1) NOT NULL DEFAULT 1', 'SELECT 1');
PREPARE stmt FROM @sql_MATERIA_ACTIVO; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @fk_FK_MATERIA_CATEGORIA := (
    SELECT COUNT(*) FROM information_schema.TABLE_CONSTRAINTS
    WHERE CONSTRAINT_SCHEMA = DATABASE() AND CONSTRAINT_NAME = 'FK_MATERIA_CATEGORIA'
);
SET @sql_FK_MATERIA_CATEGORIA := IF(@fk_FK_MATERIA_CATEGORIA = 0, 'ALTER TABLE MATERIA
        ADD CONSTRAINT FK_MATERIA_CATEGORIA
        FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA)', 'SELECT 1');
PREPARE stmt FROM @sql_FK_MATERIA_CATEGORIA; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SELECT 'CATEGORIA y vínculo en MATERIA listos.';