-- Convertido automáticamente desde db_scripts/16_07_2026/13.categoria_materia_tablas.sql
-- MySQL 8 — Academia 3.0

USE `AcademiaDB`;

/* ============================================================================
   CATEGORIA (exámenes) + FK en MATERIA
   Fecha: 16/07/2026
   ============================================================================ */

-- create if missing CATEGORIA
    CREATE TABLE IF NOT EXISTS CATEGORIA (
        IDCATEGORIA VARCHAR(50)   NOT NULL PRIMARY KEY,
        NOMBRE      VARCHAR(100)  NOT NULL,
        PORCENTAJE  DECIMAL(5,2)   NULL,
        ORDEN       INT            NOT NULL CONSTRAINT DF_CATEGORIA_ORDEN DEFAULT (0),
        ACTIVO      TINYINT(1)            NOT NULL CONSTRAINT DF_CATEGORIA_ACTIVO DEFAULT (1)
    );
    SELECT 'Tabla CATEGORIA creada.';

IF NOT EXISTS (SELECT 1 FROM CATEGORIA WHERE IDCATEGORIA = 'CAT001')
    INSERT INTO CATEGORIA (IDCATEGORIA, NOMBRE, PORCENTAJE, ORDEN, ACTIVO)
    VALUES ('CAT001', 'Habilidades', 20.0, 1, 1);
IF NOT EXISTS (SELECT 1 FROM CATEGORIA WHERE IDCATEGORIA = 'CAT002')
    INSERT INTO CATEGORIA (IDCATEGORIA, NOMBRE, PORCENTAJE, ORDEN, ACTIVO)
    VALUES ('CAT002', 'Matematica', 20.0, 2, 1);
IF NOT EXISTS (SELECT 1 FROM CATEGORIA WHERE IDCATEGORIA = 'CAT003')
    INSERT INTO CATEGORIA (IDCATEGORIA, NOMBRE, PORCENTAJE, ORDEN, ACTIVO)
    VALUES ('CAT003', 'Humanidades', 40.0, 3, 1);
IF NOT EXISTS (SELECT 1 FROM CATEGORIA WHERE IDCATEGORIA = 'CAT004')
    INSERT INTO CATEGORIA (IDCATEGORIA, NOMBRE, PORCENTAJE, ORDEN, ACTIVO)
    VALUES ('CAT004', 'Ciencias', 20.0, 4, 1);

-- TODO MySQL: add column if missing on MATERIA.IDCATEGORIA
BEGIN
    ALTER TABLE MATERIA ADD IDCATEGORIA VARCHAR(50) NULL;
    SELECT 'Columna MATERIA.IDCATEGORIA agregada.';

-- TODO MySQL: add column if missing on MATERIA.ACTIVO
BEGIN
    ALTER TABLE MATERIA ADD ACTIVO TINYINT(1) NOT NULL CONSTRAINT DF_MATERIA_ACTIVO DEFAULT (1);
    SELECT 'Columna MATERIA.ACTIVO agregada.';

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_MATERIA_CATEGORIA'
)
BEGIN
    ALTER TABLE MATERIA
        ADD CONSTRAINT FK_MATERIA_CATEGORIA
        FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA);
    SELECT 'FK_MATERIA_CATEGORIA creada.';

SELECT 'CATEGORIA y vínculo en MATERIA listos.';
