-- ============================================================================
-- Submódulos: Categorías y Materias (MOD011 Mantenedores) — MySQL 8
-- ============================================================================

USE `AcademiaDB`;

-- Migración legacy SUB020/SUB021 → SUB022/SUB023 (no-op en instalación nueva)
UPDATE SUBMODULO
SET IDSUBMODULO = 'SUB022'
WHERE IDSUBMODULO = 'SUB020'
  AND IDMODULO = 'MOD011'
  AND NOMBRE LIKE 'Categor%'
  AND NOT EXISTS (SELECT 1 FROM (SELECT IDSUBMODULO FROM SUBMODULO) x WHERE IDSUBMODULO = 'SUB022');

UPDATE USUARIO_SUBMODULO_EXCLUIDO
SET IDSUBMODULO = 'SUB022'
WHERE IDSUBMODULO = 'SUB020'
  AND EXISTS (SELECT 1 FROM SUBMODULO WHERE IDSUBMODULO = 'SUB022');

UPDATE SUBMODULO
SET IDSUBMODULO = 'SUB023'
WHERE IDSUBMODULO = 'SUB021'
  AND IDMODULO = 'MOD011'
  AND NOMBRE = 'Materias'
  AND NOT EXISTS (SELECT 1 FROM (SELECT IDSUBMODULO FROM SUBMODULO) x WHERE IDSUBMODULO = 'SUB023');

UPDATE USUARIO_SUBMODULO_EXCLUIDO
SET IDSUBMODULO = 'SUB023'
WHERE IDSUBMODULO = 'SUB021'
  AND EXISTS (SELECT 1 FROM SUBMODULO WHERE IDSUBMODULO = 'SUB023');

INSERT INTO SUBMODULO (IDSUBMODULO, NOMBRE, DESCRIPCION, ICONO, ORDEN, ACTIVO, IDMODULO)
VALUES (
    'SUB022',
    'Categorías',
    'Categorías de materias para exámenes (Habilidades, Matemática, etc.)',
    'faLayerGroup',
    5,
    1,
    'MOD011'
)
ON DUPLICATE KEY UPDATE
    NOMBRE = VALUES(NOMBRE),
    DESCRIPCION = VALUES(DESCRIPCION),
    ICONO = VALUES(ICONO),
    ORDEN = VALUES(ORDEN),
    ACTIVO = VALUES(ACTIVO),
    IDMODULO = VALUES(IDMODULO);

INSERT INTO SUBMODULO (IDSUBMODULO, NOMBRE, DESCRIPCION, ICONO, ORDEN, ACTIVO, IDMODULO)
VALUES (
    'SUB023',
    'Materias',
    'Materias / cursos vinculados a categoría',
    'faBookOpen',
    6,
    1,
    'MOD011'
)
ON DUPLICATE KEY UPDATE
    NOMBRE = VALUES(NOMBRE),
    DESCRIPCION = VALUES(DESCRIPCION),
    ICONO = VALUES(ICONO),
    ORDEN = VALUES(ORDEN),
    ACTIVO = VALUES(ACTIVO),
    IDMODULO = VALUES(IDMODULO);

SELECT 'Submódulos SUB022 y SUB023 listos.' AS info;
