/* ============================================================================
   Tablas importación de notas (Scantron / Excel)
   Ejecutar después de scripts 26_07_2026
   Fecha: 29/07/2026
   ============================================================================ */

IF OBJECT_ID('dbo.NOTA_IMPORTADA', 'U') IS NOT NULL DROP TABLE dbo.NOTA_IMPORTADA;
IF OBJECT_ID('dbo.NOTAS_IMPORTACION', 'U') IS NOT NULL DROP TABLE dbo.NOTAS_IMPORTACION;
GO

CREATE TABLE dbo.NOTAS_IMPORTACION (
    IDIMPORTACION       INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOMBRE_ARCHIVO      NVARCHAR(255) NOT NULL,
    FECHA_IMPORTACION   NVARCHAR(20) NOT NULL,
    FECHA_EXAMEN        NVARCHAR(8) NOT NULL,
    IMPORTADO_POR       NVARCHAR(50) NULL,
    IDAULA              NVARCHAR(50) NULL,
    TIPO_IMPORTACION    INT NOT NULL,
    TIPO_EXAMEN         NVARCHAR(20) NOT NULL DEFAULT 'presencial',
    TIPO_AREA_ACADEMICA NVARCHAR(10) NULL,
    ESTADO              NVARCHAR(20) NOT NULL DEFAULT 'Activo',
    CONSTRAINT FK_NOTAS_IMPORTACION_USUARIO FOREIGN KEY (IMPORTADO_POR) REFERENCES USUARIO(IDUSUARIO),
    CONSTRAINT FK_NOTAS_IMPORTACION_AULA FOREIGN KEY (IDAULA) REFERENCES AULA(IDAULA)
);
GO

CREATE TABLE dbo.NOTA_IMPORTADA (
    IDNOTA          INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    IDIMPORTACION   INT NOT NULL,
    IDUSUARIO       NVARCHAR(50) NOT NULL,
    MODO            NVARCHAR(20) NOT NULL DEFAULT 'presencial',
    PUNTAJE         DECIMAL(8,2) NOT NULL,
    PORCENTAJE      DECIMAL(8,2) NOT NULL,
    CORRECTAS       INT NOT NULL DEFAULT 0,
    INCORRECTAS     INT NOT NULL DEFAULT 0,
    NO_RESPUESTA    INT NOT NULL DEFAULT 0,
    DETALLE_AREAS   NVARCHAR(MAX) NULL,
    ACT             DECIMAL(8,2) NOT NULL DEFAULT 0,
    HM              DECIMAL(8,2) NOT NULL DEFAULT 0,
    HV              DECIMAL(8,2) NOT NULL DEFAULT 0,
    ARIT            DECIMAL(8,2) NOT NULL DEFAULT 0,
    GEO             DECIMAL(8,2) NOT NULL DEFAULT 0,
    ALGE            DECIMAL(8,2) NOT NULL DEFAULT 0,
    TRIGO           DECIMAL(8,2) NOT NULL DEFAULT 0,
    LENGUA          DECIMAL(8,2) NOT NULL DEFAULT 0,
    LIT             DECIMAL(8,2) NOT NULL DEFAULT 0,
    PSI             DECIMAL(8,2) NOT NULL DEFAULT 0,
    CIV             DECIMAL(8,2) NOT NULL DEFAULT 0,
    HP              DECIMAL(8,2) NOT NULL DEFAULT 0,
    HU              DECIMAL(8,2) NOT NULL DEFAULT 0,
    GEO_L           DECIMAL(8,2) NOT NULL DEFAULT 0,
    ECO             DECIMAL(8,2) NOT NULL DEFAULT 0,
    FILO            DECIMAL(8,2) NOT NULL DEFAULT 0,
    FIS             DECIMAL(8,2) NOT NULL DEFAULT 0,
    QUI             DECIMAL(8,2) NOT NULL DEFAULT 0,
    BIO             DECIMAL(8,2) NOT NULL DEFAULT 0,
    CONSTRAINT FK_NOTA_IMPORTADA_IMPORT FOREIGN KEY (IDIMPORTACION) REFERENCES NOTAS_IMPORTACION(IDIMPORTACION),
    CONSTRAINT FK_NOTA_IMPORTADA_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
    CONSTRAINT UQ_NOTA_IMPORTADA_EST UNIQUE (IDIMPORTACION, IDUSUARIO)
);
GO

CREATE INDEX IX_NOTAS_IMPORTACION_FECHA ON NOTAS_IMPORTACION (FECHA_EXAMEN, IDAULA, TIPO_IMPORTACION);
CREATE INDEX IX_NOTA_IMPORTADA_IMPORT ON NOTA_IMPORTADA (IDIMPORTACION);
GO

PRINT 'Tablas NOTAS_IMPORTACION y NOTA_IMPORTADA listas.';
GO
