-- Convertido automáticamente desde db_scripts/22_06_2026/esquema_completo.sql
-- MySQL 8 — Academia 3.0

USE `AcademiaDB`;

SET FOREIGN_KEY_CHECKS = 0;

/* ============================================================================
   PROYECTO ACADÉMICO - ESQUEMA COMPLETO (SQL Server)
   ----------------------------------------------------------------------------
   CONVENCIONES (aplican a TODO el proyecto):
     - IDs            : VARCHAR(50)
     - Tablas/columnas: MAYÚSCULAS
     - FECHA          : CHAR(8)  formato DDMMYYYY   (ej. 15032000 = 15/03/2000)
     - HORA           : CHAR(8)  formato HH:MM:SS   (ej. 08:30:00)
     - Fecha y hora SIEMPRE en columnas separadas (mejor control).
     - Los CHECK validan el formato a nivel de base de datos.
   ============================================================================ */

/* ----------------------------------------------------------------------------
   0) LIMPIEZA (orden inverso de dependencias) - permite reejecutar el script
   ---------------------------------------------------------------------------- */

DROP PROCEDURE IF EXISTS usp_validate_user;

DROP TABLE IF EXISTS NOTIFICACIONMEMBRESIA;
DROP TABLE IF EXISTS PAGOMEMBRESIA;
DROP TABLE IF EXISTS MEMBRESIA;
DROP TABLE IF EXISTS METODO_PAGO;
DROP TABLE IF EXISTS PROMOCIONES;
DROP TABLE IF EXISTS TURNO;
DROP TABLE IF EXISTS AULA;
DROP TABLE IF EXISTS `PLAN`;
DROP TABLE IF EXISTS LIBRO_ACCESO;
DROP TABLE IF EXISTS LIBRO_MATERIA;
DROP TABLE IF EXISTS LIBRO;
DROP TABLE IF EXISTS CUEST_RESPUESTA;
DROP TABLE IF EXISTS ALTERNATIVA_CUEST;
DROP TABLE IF EXISTS PREGUNTA_CUEST;
DROP TABLE IF EXISTS CUESTIONARIO;
DROP TABLE IF EXISTS ASISTENCIA;
DROP TABLE IF EXISTS ACTA_ASISTENCIA;
DROP TABLE IF EXISTS RESPUESTA_ALUMNO;
DROP TABLE IF EXISTS INTENTO_EXAMEN;
DROP TABLE IF EXISTS ALTERNATIVA;
DROP TABLE IF EXISTS PREGUNTA;
DROP TABLE IF EXISTS EXAMEN;
DROP TABLE IF EXISTS MATERIA;
DROP TABLE IF EXISTS USUARIO_MODULO;
DROP TABLE IF EXISTS GRUPO_MODULO;
DROP TABLE IF EXISTS TIPO_PERMISO;
DROP TABLE IF EXISTS SUBMODULO;
DROP TABLE IF EXISTS MODULO;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS TIPOUSUARIO;

/* ============================================================================
   1) USUARIOS Y CONTROL DE ACCESO
   ============================================================================ */

CREATE TABLE IF NOT EXISTS TIPOUSUARIO (
    IDTIPOUSUARIO   VARCHAR(50)    NOT NULL PRIMARY KEY,
    DESCRIPCION     VARCHAR(255)   NOT NULL
);

CREATE TABLE IF NOT EXISTS USUARIO (
    IDUSUARIO           VARCHAR(50)    NOT NULL PRIMARY KEY,
    CONTRA              VARCHAR(255)   NOT NULL,   -- guardar HASH, no texto plano
    NOMBRE              VARCHAR(100)   NOT NULL,
    APELLIDO            VARCHAR(100)   NOT NULL,
    DNI                 VARCHAR(20)    NOT NULL UNIQUE,
    FECHANACIMIENTO     CHAR(8)         NULL,
    DIRECCION           VARCHAR(255)   NULL,
    ESTADO              VARCHAR(50)    NOT NULL DEFAULT 'Activo',
    DISTRITO            VARCHAR(100)   NULL,
    COLEGIO             VARCHAR(150)   NULL,
    GRADO               VARCHAR(50)    NULL,
    FECHAACTIVO         CHAR(8)         NULL,
    EMAIL               VARCHAR(150)   NOT NULL UNIQUE,
    TELPERSONAL         VARCHAR(20)    NULL,
    TELAPODERADO        VARCHAR(20)    NULL,
    SITUACIONACADEMICA  VARCHAR(100)   NULL,
    IDTIPOUSUARIO VARCHAR(50) NOT NULL,

    FOREIGN KEY (IDTIPOUSUARIO) REFERENCES TIPOUSUARIO(IDTIPOUSUARIO)
);
CREATE INDEX IX_USUARIO_TIPO ON USUARIO(IDTIPOUSUARIO);

CREATE TABLE IF NOT EXISTS MODULO (
    IDMODULO            VARCHAR(50)    NOT NULL PRIMARY KEY,
    NOMBRE              VARCHAR(100)   NOT NULL,
    DESCRIPCION         VARCHAR(255)   NULL,
    ICONO               VARCHAR(100)   NULL,
    ORDEN               INT             NULL,
    ACTIVO              TINYINT(1)             NOT NULL DEFAULT 1,
    FECHACREACION       CHAR(8)         NULL,
    FECHAACTUALIZACION  CHAR(8)         NULL
);

CREATE TABLE IF NOT EXISTS SUBMODULO (
    IDSUBMODULO     VARCHAR(50)    NOT NULL PRIMARY KEY,
    NOMBRE          VARCHAR(100)   NOT NULL,
    DESCRIPCION     VARCHAR(255)   NULL,
    ICONO           VARCHAR(100)   NULL,
    ORDEN           INT             NULL,
    ACTIVO          TINYINT(1)             NOT NULL DEFAULT 1,
    IDMODULO VARCHAR(50) NOT NULL,

    FOREIGN KEY (IDMODULO) REFERENCES MODULO(IDMODULO)
);
CREATE INDEX IX_SUBMODULO_MODULO ON SUBMODULO(IDMODULO);

CREATE TABLE IF NOT EXISTS TIPO_PERMISO (
    IDTIPOPERMISO   VARCHAR(50)    NOT NULL PRIMARY KEY,
    DESCRIPCION     VARCHAR(255)   NOT NULL    -- ej. VER, CREAR, EDITAR, ELIMINAR
);

-- Permisos por ROL (tipo de usuario) sobre un módulo
CREATE TABLE IF NOT EXISTS GRUPO_MODULO (
    IDGRUPOMODULO   VARCHAR(50)    NOT NULL PRIMARY KEY,
    IDTIPOUSUARIO VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDTIPOUSUARIO) REFERENCES TIPOUSUARIO(IDTIPOUSUARIO),
    IDMODULO VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDMODULO) REFERENCES MODULO(IDMODULO),
    IDTIPOPERMISO VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDTIPOPERMISO) REFERENCES TIPO_PERMISO(IDTIPOPERMISO),
    CONSTRAINT UQ_GRUPO_MODULO UNIQUE (IDTIPOUSUARIO, IDMODULO, IDTIPOPERMISO)
);

-- Permisos específicos por USUARIO sobre un módulo (excepciones)
CREATE TABLE IF NOT EXISTS USUARIO_MODULO (
    IDUSUARIOMODULO VARCHAR(50)    NOT NULL PRIMARY KEY,
    IDUSUARIO VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
    IDMODULO VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDMODULO) REFERENCES MODULO(IDMODULO),
    IDTIPOPERMISO VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDTIPOPERMISO) REFERENCES TIPO_PERMISO(IDTIPOPERMISO),
    CONSTRAINT UQ_USUARIO_MODULO UNIQUE (IDUSUARIO, IDMODULO, IDTIPOPERMISO)
);

/* ============================================================================
   2) MATERIAS, EXÁMENES Y PREGUNTAS
   ============================================================================ */

CREATE TABLE IF NOT EXISTS MATERIA (
    IDMATERIA   VARCHAR(50)    NOT NULL PRIMARY KEY,
    CODIGO      VARCHAR(50)    NULL,
    NOMBRE      VARCHAR(150)   NOT NULL
);

CREATE TABLE IF NOT EXISTS EXAMEN (
    IDEXAMEN        VARCHAR(50)    NOT NULL PRIMARY KEY,
    TITULO          VARCHAR(200)   NOT NULL,
    DESCRIPCION     LONGTEXT   NULL,
    TIPO            INT             NULL,   -- catálogo de tipos de examen (1,2,3...)
    DURACIONMIN     INT             NULL,
    PUNTAJETOTAL    DECIMAL(6,2)    NULL,
    PUNTAJEAPROBADO DECIMAL(6,2)    NULL,
    FECHAINICIO     CHAR(8)         NULL,
    FECHAFIN        CHAR(8)         NULL,
    HORAINICIO      CHAR(8)         NULL,
    HORAFIN         CHAR(8)         NULL,
    TIEMPOLIMITE    CHAR(8)         NULL,
    INTENTOSMAX     INT             NULL DEFAULT 1,
    VISIBLE         TINYINT(1)             NOT NULL DEFAULT 1,
    IDUSUARIO VARCHAR(50) NOT NULL,

    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)   -- docente que lo crea
);
CREATE INDEX IX_EXAMEN_USUARIO ON EXAMEN(IDUSUARIO);

CREATE TABLE IF NOT EXISTS PREGUNTA (
    IDPREGUNTA      VARCHAR(50)    NOT NULL PRIMARY KEY,
    TITULO          VARCHAR(255)   NOT NULL,
    DESCRIPCION     LONGTEXT   NULL,
    PUNTAJE         DECIMAL(6,2)    NULL,
    ORDEN           INT             NULL,
    IMAGEURL        VARCHAR(255)   NULL,
    IDEXAMEN VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDEXAMEN) REFERENCES EXAMEN(IDEXAMEN),
    IDMATERIA VARCHAR(50) NULL,
    FOREIGN KEY (IDMATERIA) REFERENCES MATERIA(IDMATERIA)
);
CREATE INDEX IX_PREGUNTA_EXAMEN  ON PREGUNTA(IDEXAMEN);
CREATE INDEX IX_PREGUNTA_MATERIA ON PREGUNTA(IDMATERIA);

CREATE TABLE IF NOT EXISTS ALTERNATIVA (
    IDALTERNATIVA   VARCHAR(50)    NOT NULL PRIMARY KEY,
    DESCRIPCION     LONGTEXT   NOT NULL,
    ESCORRECTA      TINYINT(1)             NOT NULL DEFAULT 0,
    ORDEN           INT             NULL,
    IMAGEURL        VARCHAR(255)   NULL,
    IDPREGUNTA VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDPREGUNTA) REFERENCES PREGUNTA(IDPREGUNTA)
);
CREATE INDEX IX_ALTERNATIVA_PREGUNTA ON ALTERNATIVA(IDPREGUNTA);

CREATE TABLE IF NOT EXISTS INTENTO_EXAMEN (
    IDINTENTOEXAMEN VARCHAR(50)    NOT NULL PRIMARY KEY,
    NUMEROINTENTO   INT             NOT NULL DEFAULT 1,
    FECHAINICIO     CHAR(8)         NULL,
    HORAINICIO      CHAR(8)         NULL,
    FECHAFIN        CHAR(8)         NULL,
    HORAFIN         CHAR(8)         NULL,
    PUNTAJEOBTENIDO DECIMAL(6,2)    NULL,
    CANTCORRECTAS   INT             NULL DEFAULT 0,
    CANTINCORRECTAS INT             NULL DEFAULT 0,
    CANTSINRESPONDER INT            NULL DEFAULT 0,
    ESTADO          INT             NULL,       -- ej. 0=en curso, 1=finalizado
    APROBADO        TINYINT(1)             NULL,
    IDEXAMEN VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDEXAMEN) REFERENCES EXAMEN(IDEXAMEN),
    IDUSUARIO VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);
CREATE INDEX IX_INTENTO_EXAMEN_EXAMEN  ON INTENTO_EXAMEN(IDEXAMEN);
CREATE INDEX IX_INTENTO_EXAMEN_USUARIO ON INTENTO_EXAMEN(IDUSUARIO);

CREATE TABLE IF NOT EXISTS RESPUESTA_ALUMNO (
    IDRESPUESTAALUMNO VARCHAR(50)  NOT NULL PRIMARY KEY,
    PUNTAJEOBTENIDO   DECIMAL(6,2)  NULL,
    RESPABIERTA       LONGTEXT NULL,       -- para preguntas abiertas
    IDINTENTOEXAMEN VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDINTENTOEXAMEN) REFERENCES INTENTO_EXAMEN(IDINTENTOEXAMEN),
    IDPREGUNTA VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDPREGUNTA) REFERENCES PREGUNTA(IDPREGUNTA),
    IDALTERNATIVA VARCHAR(50) NULL,
    FOREIGN KEY (IDALTERNATIVA) REFERENCES ALTERNATIVA(IDALTERNATIVA)
);
CREATE INDEX IX_RESP_ALUMNO_INTENTO ON RESPUESTA_ALUMNO(IDINTENTOEXAMEN);
CREATE INDEX IX_RESP_ALUMNO_PREGUNTA ON RESPUESTA_ALUMNO(IDPREGUNTA);

/* ============================================================================
   3) ASISTENCIA
   ============================================================================ */

CREATE TABLE IF NOT EXISTS ACTA_ASISTENCIA (
    IDACTAASISTENCIA VARCHAR(50)   NOT NULL PRIMARY KEY,
    FECHAINICIO      CHAR(8)        NULL,
    HORAINICIO       CHAR(8)        NULL,
    FECHAFINAL       CHAR(8)        NULL,
    HORAFINAL        CHAR(8)        NULL
);

CREATE TABLE IF NOT EXISTS ASISTENCIA (
    IDASISTENCIA     VARCHAR(50)   NOT NULL PRIMARY KEY,
    FECHAREGISTRO    CHAR(8)        NULL,
    HORAINICIO       CHAR(8)        NULL,
    FECHAFINAL       CHAR(8)        NULL,
    HORAFINAL        CHAR(8)        NULL,
    ESTADO           VARCHAR(50)   NULL,       -- ej. Presente, Tarde, Ausente
    JUSTIFICADO      TINYINT(1)            NOT NULL DEFAULT 0,
    IDUSUARIO VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
    IDACTAASISTENCIA VARCHAR(50) NULL,
    FOREIGN KEY (IDACTAASISTENCIA) REFERENCES ACTA_ASISTENCIA(IDACTAASISTENCIA)
);
CREATE INDEX IX_ASISTENCIA_USUARIO ON ASISTENCIA(IDUSUARIO);
CREATE INDEX IX_ASISTENCIA_ACTA    ON ASISTENCIA(IDACTAASISTENCIA);

/* ============================================================================
   4) CUESTIONARIOS (flujo independiente del examen)
   ============================================================================ */

CREATE TABLE IF NOT EXISTS CUESTIONARIO (
    IDCUESTIONARIO     VARCHAR(50)  NOT NULL PRIMARY KEY,
    TITULO             VARCHAR(200) NOT NULL,
    DESCRIPCION        LONGTEXT NULL,
    FECHAINICIO        CHAR(8)       NULL,
    HORAINICIO         CHAR(8)       NULL,
    FECHAFINAL         CHAR(8)       NULL,
    HORAFINAL          CHAR(8)       NULL,
    ACTIVO             TINYINT(1)           NOT NULL DEFAULT 1,
    ENLACECUESTIONARIO VARCHAR(255) NULL
);

CREATE TABLE IF NOT EXISTS PREGUNTA_CUEST (
    IDPREGUNTACUEST VARCHAR(50)    NOT NULL PRIMARY KEY,
    TITULO          VARCHAR(255)   NOT NULL,
    DESCRIPCION     LONGTEXT   NULL,
    IDCUESTIONARIO VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDCUESTIONARIO) REFERENCES CUESTIONARIO(IDCUESTIONARIO)
);
CREATE INDEX IX_PREGUNTA_CUEST ON PREGUNTA_CUEST(IDCUESTIONARIO);

CREATE TABLE IF NOT EXISTS ALTERNATIVA_CUEST (
    IDALTERNATIVACUEST VARCHAR(50) NOT NULL PRIMARY KEY,
    DESCRIPCION        LONGTEXT NOT NULL,
    IDPREGUNTACUEST VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDPREGUNTACUEST) REFERENCES PREGUNTA_CUEST(IDPREGUNTACUEST)
);
CREATE INDEX IX_ALT_CUEST_PREGUNTA ON ALTERNATIVA_CUEST(IDPREGUNTACUEST);

CREATE TABLE IF NOT EXISTS CUEST_RESPUESTA (
    IDCUESTRESPUESTA   VARCHAR(50) NOT NULL PRIMARY KEY,
    FECHAREGISTRO      CHAR(8)      NULL,
    HORAREGISTRO       CHAR(8)      NULL,
    IDCUESTIONARIO VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDCUESTIONARIO) REFERENCES CUESTIONARIO(IDCUESTIONARIO),
    IDALTERNATIVACUEST VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDALTERNATIVACUEST) REFERENCES ALTERNATIVA_CUEST(IDALTERNATIVACUEST)
);
CREATE INDEX IX_CUEST_RESP_CUEST ON CUEST_RESPUESTA(IDCUESTIONARIO);
CREATE INDEX IX_CUEST_RESP_ALT   ON CUEST_RESPUESTA(IDALTERNATIVACUEST);

/* ============================================================================
   5) BIBLIOTECA
   ============================================================================ */

CREATE TABLE IF NOT EXISTS LIBRO (
    IDLIBRO        VARCHAR(50)     NOT NULL PRIMARY KEY,
    TITULO         VARCHAR(200)    NOT NULL,
    DESCRIPCION    LONGTEXT    NULL,
    AUTOR          VARCHAR(150)    NULL,
    ANIOPUBLICACION VARCHAR(4)     NULL,
    URLCONTENIDO   VARCHAR(255)    NULL,
    IMGPORTADA     VARCHAR(255)    NULL,
    ESTADO         VARCHAR(50)     NULL DEFAULT 'Activo'
);

-- Relación N:M  (un libro puede pertenecer a varias materias)
CREATE TABLE IF NOT EXISTS LIBRO_MATERIA (
    IDLIBROMATERIA VARCHAR(50)     NOT NULL PRIMARY KEY,
    IDLIBRO VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDLIBRO) REFERENCES LIBRO(IDLIBRO),
    IDMATERIA VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDMATERIA) REFERENCES MATERIA(IDMATERIA),
    CONSTRAINT UQ_LIBRO_MATERIA UNIQUE (IDLIBRO, IDMATERIA)
);

CREATE TABLE IF NOT EXISTS LIBRO_ACCESO (
    IDLIBROACCESO  VARCHAR(50)     NOT NULL PRIMARY KEY,
    FECHAINGRESO   CHAR(8)          NULL,
    HORAINGRESO    CHAR(8)          NULL,
    IDUSUARIO VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
    IDLIBRO VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDLIBRO) REFERENCES LIBRO(IDLIBRO)
);
CREATE INDEX IX_LIBRO_ACCESO_USUARIO ON LIBRO_ACCESO(IDUSUARIO);
CREATE INDEX IX_LIBRO_ACCESO_LIBRO   ON LIBRO_ACCESO(IDLIBRO);

/* ============================================================================
   6) MEMBRESÍAS, PAGOS Y CATÁLOGOS
   ============================================================================ */

CREATE TABLE IF NOT EXISTS PLAN (
    IDPLAN       VARCHAR(50)   NOT NULL PRIMARY KEY,
    NOMBRE       VARCHAR(100)  NOT NULL,
    DESCRIPCION  VARCHAR(255)  NULL,
    DURACIONDIAS INT            NULL,
    PRECIO       DECIMAL(10,2)  NULL,
    ACTIVO       TINYINT(1)            NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS AULA (
    IDAULA             VARCHAR(50)   NOT NULL PRIMARY KEY,
    NOMBRE             VARCHAR(100)  NOT NULL,
    DESCRIPCION        LONGTEXT  NULL,
    CAPACIDAD          INT            NULL,
    ACTIVO             TINYINT(1)            NOT NULL DEFAULT 1,
    ENLACEVIRTUAL      VARCHAR(255)  NULL,
    ENLACECUESTIONARIO VARCHAR(255)  NULL
);

CREATE TABLE IF NOT EXISTS TURNO (
    IDTURNO     VARCHAR(50)   NOT NULL PRIMARY KEY,
    DESCRIPCION VARCHAR(100)  NOT NULL   -- ej. Mañana, Tarde, Noche
);

CREATE TABLE IF NOT EXISTS PROMOCIONES (
    IDPROMOCION VARCHAR(50)   NOT NULL PRIMARY KEY,
    TITULO      VARCHAR(150)  NOT NULL,
    DESCRIPCION VARCHAR(255)  NULL,
    DESCUENTO   INT            NULL       -- porcentaje
);

CREATE TABLE IF NOT EXISTS METODO_PAGO (
    IDMETODOPAGO VARCHAR(50)  NOT NULL PRIMARY KEY,
    TITULO       VARCHAR(100) NOT NULL,
    DESCRIPCION  VARCHAR(255) NULL,
    ACTIVO       TINYINT(1)           NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS MEMBRESIA (
    IDMEMBRESIA    VARCHAR(50)  NOT NULL PRIMARY KEY,
    FECHAINICIO    CHAR(8)       NULL,
    FECHAFIN       CHAR(8)       NULL,
    ESTADOMIEMBRO  INT           NULL,
    CICLO          INT           NULL,
    MONTOTOTAL     DECIMAL(10,2) NULL,
    OBSERVACIONES  LONGTEXT NULL,
    FECHAREGISTRO  CHAR(8)       NULL,
    HORAREGISTRO   CHAR(8)       NULL,
    FECHAPAGO      CHAR(8)       NULL,
    IDPLAN VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDPLAN) REFERENCES `PLAN`(IDPLAN),
    IDAULA VARCHAR(50) NULL,
    FOREIGN KEY (IDAULA) REFERENCES AULA(IDAULA),
    IDTURNO VARCHAR(50) NULL,
    FOREIGN KEY (IDTURNO) REFERENCES TURNO(IDTURNO),
    IDPROMOCION VARCHAR(50) NULL,
    FOREIGN KEY (IDPROMOCION) REFERENCES PROMOCIONES(IDPROMOCION),
    IDUSUARIO VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),   -- titular
    REGISTRADOPOR VARCHAR(50) NULL,
    FOREIGN KEY (REGISTRADOPOR) REFERENCES USUARIO(IDUSUARIO)    -- quien registra
);
CREATE INDEX IX_MEMBRESIA_USUARIO ON MEMBRESIA(IDUSUARIO);
CREATE INDEX IX_MEMBRESIA_PLAN    ON MEMBRESIA(IDPLAN);

CREATE TABLE IF NOT EXISTS PAGOMEMBRESIA (
    IDPAGOMEMBRESIA VARCHAR(50)  NOT NULL PRIMARY KEY,
    MONTO           DECIMAL(10,2) NOT NULL,
    COMPROBANTEURL  VARCHAR(255) NULL,
    FECHAPAGO       CHAR(8)       NULL,
    HORAPAGO        CHAR(8)       NULL,
    OBSERVACIONES   LONGTEXT NULL,
    IDMEMBRESIA VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDMEMBRESIA) REFERENCES MEMBRESIA(IDMEMBRESIA),
    IDMETODOPAGO VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDMETODOPAGO) REFERENCES METODO_PAGO(IDMETODOPAGO),
    IDUSUARIO VARCHAR(50) NULL,
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)   -- quien registra el pago
);
CREATE INDEX IX_PAGOMEMBRESIA_MEMBRESIA ON PAGOMEMBRESIA(IDMEMBRESIA);

CREATE TABLE IF NOT EXISTS NOTIFICACIONMEMBRESIA (
    IDNOTIFICACIONMEMBRESIA VARCHAR(50) NOT NULL PRIMARY KEY,
    TIPO          VARCHAR(20)  NULL,
    MENSAJE       LONGTEXT NULL,
    FECHACREACION CHAR(8)       NULL,
    HORACREACION  CHAR(8)       NULL,
    FECHALIMITE   CHAR(8)       NULL,
    ACTIVA        TINYINT(1)           NOT NULL DEFAULT 1,
    IDMEMBRESIA VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDMEMBRESIA) REFERENCES MEMBRESIA(IDMEMBRESIA),
    IDUSUARIO VARCHAR(50) NOT NULL,
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);
CREATE INDEX IX_NOTIF_MEMBRESIA ON NOTIFICACIONMEMBRESIA(IDMEMBRESIA);
CREATE INDEX IX_NOTIF_USUARIO   ON NOTIFICACIONMEMBRESIA(IDUSUARIO);

/* ============================================================================
   7) DATOS INICIALES (SEED)
   ============================================================================ */

INSERT INTO TIPOUSUARIO (IDTIPOUSUARIO, DESCRIPCION) VALUES
('1', 'Estudiante'),
('2', 'Docente'),
('3', 'Administrador');

INSERT INTO USUARIO
(IDUSUARIO, CONTRA, NOMBRE, APELLIDO, DNI, FECHANACIMIENTO, DIRECCION, ESTADO, DISTRITO, COLEGIO, GRADO, FECHAACTIVO, EMAIL, TELPERSONAL, TELAPODERADO, SITUACIONACADEMICA, IDTIPOUSUARIO)
VALUES
('1', '1234', 'Carlos', 'Ramirez', '12345678', '15032000', 'Av. Lima 123',      'Activo', 'Miraflores', 'Colegio San Jose', '5to', '01012024', 'carlos@gmail.com', '987654321', '912345678', 'Regular', '1'),
('2', '1234', 'Maria',  'Lopez',   '87654321', '20071990', 'Jr. Cusco 456',     'Activo', 'San Isidro', NULL,               NULL,  '01012024', 'maria@gmail.com',  '998877665', NULL,        NULL,      '2'),
('3', '1234', 'Pedro',  'Torres',  '11223344', '10111985', 'Calle Arequipa 789','Activo', 'Surco',      NULL,               NULL,  '01012024', 'pedro@gmail.com',  '977665544', NULL,        NULL,      '3');

/* ============================================================================
   8) STORED PROCEDURE DE VALIDACIÓN
   ----------------------------------------------------------------------------
   NOTA: la contraseña se compara en texto plano (igual que tu versión actual).
   Para producción se recomienda guardar y comparar un HASH.
   ============================================================================ */

DROP PROCEDURE IF EXISTS usp_validate_user;

DELIMITER $$

CREATE PROCEDURE usp_validate_user(
    IN p_username VARCHAR(50),
    IN p_password VARCHAR(255)
)
main: BEGIN
    DECLARE v_IDTIPOUSUARIO VARCHAR(50);

    SELECT IDTIPOUSUARIO INTO v_IDTIPOUSUARIO
    FROM USUARIO
    WHERE IDUSUARIO = p_username
      AND CONTRA = p_password
      AND ESTADO = 'Activo'
    LIMIT 1;

    IF v_IDTIPOUSUARIO IS NOT NULL THEN
        SELECT
            1 AS is_valid,
            CASE v_IDTIPOUSUARIO
                WHEN '1' THEN 'estudiante'
                WHEN '2' THEN 'docente'
                WHEN '3' THEN 'administrador'
                ELSE 'estudiante'
            END AS role;
    ELSE
        SELECT 0 AS is_valid, 'estudiante' AS role;
    END IF;
END$$

DELIMITER ;

SET FOREIGN_KEY_CHECKS = 1;
