-- ============================================================================
-- CLASE_GRABADA — enlaces a clases grabadas por salón y materia — MySQL 8
-- Fecha: 18/07/2026
-- ============================================================================

USE `AcademiaDB`;

CREATE TABLE IF NOT EXISTS CLASE_GRABADA (
    IDCLASEGRABADA   VARCHAR(50)  NOT NULL PRIMARY KEY,
    IDAULA           VARCHAR(50)  NOT NULL,
    IDMATERIA        VARCHAR(50)  NOT NULL,
    ENLACE           VARCHAR(500) NOT NULL,
    DETALLES         VARCHAR(500) NOT NULL,
    FECHASUBIDA      CHAR(8)      NULL,
    HORASUBIDA       CHAR(8)      NULL,
    ESTADO           VARCHAR(50)  NULL DEFAULT 'Activo',
    CREADO_POR       VARCHAR(50)  NULL,
    FECHACREACION    CHAR(8)      NULL,
    HORACREACION     CHAR(8)      NULL,
    MODIFICADO_POR   VARCHAR(50)  NULL,
    FECHAMODIFICACION CHAR(8)     NULL,
    HORAMODIFICACION CHAR(8)      NULL,
    CONSTRAINT FK_CLASE_GRABADA_AULA FOREIGN KEY (IDAULA) REFERENCES AULA(IDAULA),
    CONSTRAINT FK_CLASE_GRABADA_MATERIA FOREIGN KEY (IDMATERIA) REFERENCES MATERIA(IDMATERIA)
);

CREATE INDEX IX_CLASE_GRABADA_AULA ON CLASE_GRABADA(IDAULA);
CREATE INDEX IX_CLASE_GRABADA_MATERIA ON CLASE_GRABADA(IDMATERIA);
CREATE INDEX IX_CLASE_GRABADA_ESTADO ON CLASE_GRABADA(ESTADO);

SELECT 'Tabla CLASE_GRABADA lista.' AS info;
