/* ============================================================================
   MENSUALIDAD_CUOTA + IDCUOTA en PAGOMENSUALIDAD
   Cobros mensuales por periodo (matrículas nuevas)
   Fecha: 15/08/2026
   ============================================================================ */

IF OBJECT_ID('dbo.MENSUALIDAD_CUOTA', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MENSUALIDAD_CUOTA (
        IDCUOTA           NVARCHAR(50)   NOT NULL PRIMARY KEY,
        IDMENSUALIDAD     NVARCHAR(50)   NOT NULL,
        NUMERO            INT            NOT NULL,
        FECHAINICIO       CHAR(8)        NOT NULL,
        FECHAFIN          CHAR(8)        NOT NULL,
        MONTO             DECIMAL(10,2)  NOT NULL CONSTRAINT DF_CUOTA_MONTO DEFAULT 0,
        ESTADO            NVARCHAR(50)   NOT NULL CONSTRAINT DF_CUOTA_ESTADO DEFAULT N'Pendiente',
        CREADO_POR        NVARCHAR(50)   NULL,
        FECHACREACION     CHAR(8)        NULL,
        HORACREACION      CHAR(8)        NULL,
        MODIFICADO_POR    NVARCHAR(50)   NULL,
        FECHAMODIFICACION CHAR(8)        NULL,
        HORAMODIFICACION  CHAR(8)        NULL,
        CONSTRAINT FK_CUOTA_MENSUALIDAD FOREIGN KEY (IDMENSUALIDAD)
            REFERENCES dbo.MENSUALIDAD(IDMENSUALIDAD) ON DELETE CASCADE,
        CONSTRAINT UQ_CUOTA_MENSUALIDAD_NUM UNIQUE (IDMENSUALIDAD, NUMERO)
    );
    CREATE INDEX IX_CUOTA_MENSUALIDAD ON dbo.MENSUALIDAD_CUOTA(IDMENSUALIDAD);
    CREATE INDEX IX_CUOTA_FECHAS ON dbo.MENSUALIDAD_CUOTA(FECHAINICIO, FECHAFIN);
END
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.columns
    WHERE object_id = OBJECT_ID('dbo.PAGOMENSUALIDAD') AND name = 'IDCUOTA'
)
BEGIN
    ALTER TABLE dbo.PAGOMENSUALIDAD ADD IDCUOTA NVARCHAR(50) NULL;
    ALTER TABLE dbo.PAGOMENSUALIDAD
        ADD CONSTRAINT FK_PAGO_CUOTA FOREIGN KEY (IDCUOTA)
        REFERENCES dbo.MENSUALIDAD_CUOTA(IDCUOTA);
    CREATE INDEX IX_PAGO_CUOTA ON dbo.PAGOMENSUALIDAD(IDCUOTA);
END
GO

PRINT 'MENSUALIDAD_CUOTA y PAGOMENSUALIDAD.IDCUOTA listos.';
GO
