-- ============================================================================
-- BIBLIOTECA — columnas y relación libro ↔ salón — MySQL 8
-- Fecha: 14/07/2026
-- ============================================================================

USE `AcademiaDB`;

-- Fecha de subida (DDMMYYYY)
SET @col_LIBRO_FECHASUBIDA := (
    SELECT COUNT(*) FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'LIBRO' AND COLUMN_NAME = 'FECHASUBIDA'
);
SET @sql_LIBRO_FECHASUBIDA := IF(
    @col_LIBRO_FECHASUBIDA = 0,
    'ALTER TABLE LIBRO ADD FECHASUBIDA CHAR(8) NULL',
    'SELECT 1'
);
PREPARE stmt FROM @sql_LIBRO_FECHASUBIDA;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Relación N:M libro ↔ aula (salones con acceso)
CREATE TABLE IF NOT EXISTS LIBRO_AULA (
    IDLIBROAULA VARCHAR(50) NOT NULL PRIMARY KEY,
    IDLIBRO     VARCHAR(50) NOT NULL,
    IDAULA      VARCHAR(50) NOT NULL,
    CONSTRAINT UQ_LIBRO_AULA UNIQUE (IDLIBRO, IDAULA),
    CONSTRAINT FK_LIBRO_AULA_LIBRO FOREIGN KEY (IDLIBRO) REFERENCES LIBRO(IDLIBRO),
    CONSTRAINT FK_LIBRO_AULA_AULA  FOREIGN KEY (IDAULA) REFERENCES AULA(IDAULA)
);

CREATE INDEX IX_LIBRO_AULA_LIBRO ON LIBRO_AULA(IDLIBRO);
CREATE INDEX IX_LIBRO_AULA_AULA  ON LIBRO_AULA(IDAULA);
