-- ========================================
-- SCRIPT: Creación de Tablas de Módulos
-- Fecha: 2026-05-09
-- Descripción: Tablas para gestión escalable de acceso a módulos
-- ========================================

-- 1. Tabla de Módulos (Módulos principales)
IF OBJECT_ID('MODULO', 'U') IS NOT NULL 
    DROP TABLE MODULO;
GO

CREATE TABLE MODULO (
    IDMODULO            NVARCHAR(50)    PRIMARY KEY,
    NOMBRE              NVARCHAR(150)   NOT NULL UNIQUE,
    DESCRIPCION         NVARCHAR(500),
    ICONO               NVARCHAR(100),  -- Nombre del ícono (FontAwesome, etc.)
    ORDEN               INT             DEFAULT 0,
    ACTIVO              BIT             DEFAULT 1,
    FECHA_CREACION      NVARCHAR(20)    DEFAULT CONVERT(NVARCHAR(8), GETDATE(), 112) + ' ' + CONVERT(NVARCHAR(8), GETDATE(), 108),
    FECHA_ACTUALIZACION NVARCHAR(20)    DEFAULT CONVERT(NVARCHAR(8), GETDATE(), 112) + ' ' + CONVERT(NVARCHAR(8), GETDATE(), 108)
);
GO

-- 2. Tabla de Submódulos
IF OBJECT_ID('SUBMODULO', 'U') IS NOT NULL 
    DROP TABLE SUBMODULO;
GO

CREATE TABLE SUBMODULO (
    IDSUBMODULO         NVARCHAR(50)    PRIMARY KEY,
    IDMODULO            NVARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES MODULO(IDMODULO),
    NOMBRE              NVARCHAR(150)   NOT NULL,
    DESCRIPCION         NVARCHAR(500),
    ICONO               NVARCHAR(100),
    ORDEN               INT             DEFAULT 0,
    ACTIVO              BIT             DEFAULT 1,
    FECHA_CREACION      NVARCHAR(20)    DEFAULT CONVERT(NVARCHAR(8), GETDATE(), 112) + ' ' + CONVERT(NVARCHAR(8), GETDATE(), 108),
    FECHA_ACTUALIZACION NVARCHAR(20)    DEFAULT CONVERT(NVARCHAR(8), GETDATE(), 112) + ' ' + CONVERT(NVARCHAR(8), GETDATE(), 108)
);
GO

-- 3. Tabla de Permisos (Tipos de acceso escalables)
IF OBJECT_ID('TIPO_PERMISO', 'U') IS NOT NULL 
    DROP TABLE TIPO_PERMISO;
GO

CREATE TABLE TIPO_PERMISO (
    IDPERMISO           NVARCHAR(50)    PRIMARY KEY,
    NOMBRE              NVARCHAR(100)   NOT NULL UNIQUE,
    DESCRIPCION         NVARCHAR(255),
    FECHA_CREACION      NVARCHAR(20)    DEFAULT CONVERT(NVARCHAR(8), GETDATE(), 112) + ' ' + CONVERT(NVARCHAR(8), GETDATE(), 108)
);
GO

-- 4. Tabla de Asignación de Módulos a Usuarios (Principal)
IF OBJECT_ID('USUARIO_MODULO', 'U') IS NOT NULL 
    DROP TABLE USUARIO_MODULO;
GO

CREATE TABLE USUARIO_MODULO (
    IDUSUARIO_MODULO    NVARCHAR(50)    PRIMARY KEY,
    IDUSUARIO           NVARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES USUARIO(IDUSUARIO),
    IDMODULO            NVARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES MODULO(IDMODULO),
    PERMISOS            NVARCHAR(MAX),  -- JSON: ['read', 'write', 'delete', 'admin']
    FECHA_ASIGNACION    NVARCHAR(20)    DEFAULT CONVERT(NVARCHAR(8), GETDATE(), 112) + ' ' + CONVERT(NVARCHAR(8), GETDATE(), 108),
    FECHA_ACTUALIZACION NVARCHAR(20)    DEFAULT CONVERT(NVARCHAR(8), GETDATE(), 112) + ' ' + CONVERT(NVARCHAR(8), GETDATE(), 108),
    ASIGNADO_POR        NVARCHAR(50),   -- Usuario que asignó el permiso
    ACTIVO              BIT             DEFAULT 1,
    UNIQUE (IDUSUARIO, IDMODULO)
);
GO

-- 5. Tabla de Asignación de Módulos a Roles/Grupos
IF OBJECT_ID('GRUPO_MODULO', 'U') IS NOT NULL 
    DROP TABLE GRUPO_MODULO;
GO

CREATE TABLE GRUPO_MODULO (
    IDGRUPO_MODULO      NVARCHAR(50)    PRIMARY KEY,
    IDGRUPO             NVARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES TIPOUSUARIO(IDTIPOUSUARIO), -- Referencia a tipo de usuario (admin, secretario, etc.)
    IDMODULO            NVARCHAR(50)    NOT NULL FOREIGN KEY REFERENCES MODULO(IDMODULO),
    PERMISOS            NVARCHAR(MAX),  -- JSON: ['read', 'write', 'delete', 'admin']
    FECHA_ASIGNACION    NVARCHAR(20)    DEFAULT CONVERT(NVARCHAR(8), GETDATE(), 112) + ' ' + CONVERT(NVARCHAR(8), GETDATE(), 108),
    FECHA_ACTUALIZACION NVARCHAR(20)    DEFAULT CONVERT(NVARCHAR(8), GETDATE(), 112) + ' ' + CONVERT(NVARCHAR(8), GETDATE(), 108),
    ACTIVO              BIT             DEFAULT 1,
    UNIQUE (IDGRUPO, IDMODULO)
);
GO

-- Crear índices para mejorar rendimiento
CREATE INDEX IDX_SUBMODULO_MODULO ON SUBMODULO(IDMODULO);
CREATE INDEX IDX_USUARIO_MODULO_USUARIO ON USUARIO_MODULO(IDUSUARIO);
CREATE INDEX IDX_USUARIO_MODULO_MODULO ON USUARIO_MODULO(IDMODULO);
CREATE INDEX IDX_GRUPO_MODULO_GRUPO ON GRUPO_MODULO(IDGRUPO);
CREATE INDEX IDX_GRUPO_MODULO_MODULO ON GRUPO_MODULO(IDMODULO);

GO

PRINT 'Tablas de módulos creadas exitosamente';
GO
