-- Columna FOTO en USUARIO — MySQL 8
USE `AcademiaDB`;

SET @col_USUARIO_FOTO := (
    SELECT COUNT(*) FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'USUARIO' AND COLUMN_NAME = 'FOTO'
);
SET @sql_USUARIO_FOTO := IF(
    @col_USUARIO_FOTO = 0,
    'ALTER TABLE USUARIO ADD COLUMN FOTO LONGTEXT NULL',
    'SELECT 1'
);
PREPARE stmt FROM @sql_USUARIO_FOTO;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT 'Columna USUARIO.FOTO verificada.' AS info;
