-- ============================================================================
-- MENSUALIDAD_CUOTA + IDCUOTA en PAGOMENSUALIDAD — MySQL 8
-- Cobros mensuales por periodo (matrículas nuevas)
-- Fecha: 15/08/2026
-- ============================================================================

USE `AcademiaDB`;

CREATE TABLE IF NOT EXISTS MENSUALIDAD_CUOTA (
    IDCUOTA          VARCHAR(50)   NOT NULL PRIMARY KEY,
    IDMENSUALIDAD    VARCHAR(50)   NOT NULL,
    NUMERO           INT           NOT NULL,
    FECHAINICIO      CHAR(8)       NOT NULL,
    FECHAFIN         CHAR(8)       NOT NULL,
    MONTO            DECIMAL(10,2) NOT NULL DEFAULT 0,
    ESTADO           VARCHAR(50)   NOT NULL DEFAULT 'Pendiente',
    CREADO_POR       VARCHAR(50)   NULL,
    FECHACREACION    CHAR(8)       NULL,
    HORACREACION     CHAR(8)       NULL,
    MODIFICADO_POR   VARCHAR(50)   NULL,
    FECHAMODIFICACION CHAR(8)      NULL,
    HORAMODIFICACION CHAR(8)       NULL,
    CONSTRAINT FK_CUOTA_MENSUALIDAD FOREIGN KEY (IDMENSUALIDAD)
        REFERENCES MENSUALIDAD(IDMENSUALIDAD) ON DELETE CASCADE,
    CONSTRAINT UQ_CUOTA_MENSUALIDAD_NUM UNIQUE (IDMENSUALIDAD, NUMERO)
);

CREATE INDEX IX_CUOTA_MENSUALIDAD ON MENSUALIDAD_CUOTA(IDMENSUALIDAD);
CREATE INDEX IX_CUOTA_FECHAS ON MENSUALIDAD_CUOTA(FECHAINICIO, FECHAFIN);

SET @col_exists := (
    SELECT COUNT(*) FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'PAGOMENSUALIDAD'
      AND COLUMN_NAME = 'IDCUOTA'
);
SET @sql := IF(@col_exists = 0,
    'ALTER TABLE PAGOMENSUALIDAD ADD COLUMN IDCUOTA VARCHAR(50) NULL, ADD CONSTRAINT FK_PAGO_CUOTA FOREIGN KEY (IDCUOTA) REFERENCES MENSUALIDAD_CUOTA(IDCUOTA)',
    'SELECT ''Columna PAGOMENSUALIDAD.IDCUOTA ya existe'' AS info'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @idx_exists := (
    SELECT COUNT(*) FROM information_schema.STATISTICS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'PAGOMENSUALIDAD'
      AND INDEX_NAME = 'IX_PAGO_CUOTA'
);
SET @sql_idx := IF(@idx_exists = 0,
    'CREATE INDEX IX_PAGO_CUOTA ON PAGOMENSUALIDAD(IDCUOTA)',
    'SELECT ''Indice IX_PAGO_CUOTA ya existe'' AS info'
);
PREPARE stmt_idx FROM @sql_idx;
EXECUTE stmt_idx;
DEALLOCATE PREPARE stmt_idx;

SELECT 'MENSUALIDAD_CUOTA y PAGOMENSUALIDAD.IDCUOTA listos.' AS info;
