-- Convertido automáticamente desde db_scripts/07_05_2026/script.sql
-- MySQL 8 — Academia 3.0

USE `AcademiaDB`;

---- CAMBIO DE MINUSCULA A MAYUSCULA EN LOS NOMBRES DE LAS TABLAS Y CAMPOS

IF COL_LENGTH('TIPOUSUARIO', 'idTipoUsuario') IS NOT NULL
BEGIN
    ALTER TABLE `TIPOUSUARIO` RENAME COLUMN `idTipoUsuario` TO `IDTIPOUSUARIO`;

IF COL_LENGTH('TIPOUSUARIO', 'descripcion') IS NOT NULL
BEGIN
    ALTER TABLE `TIPOUSUARIO` RENAME COLUMN `idTipoUsuario` TO `IDTIPOUSUARIO`;

IF COL_LENGTH('USUARIO', 'idUsuario') IS NOT NULL
BEGIN
    ALTER TABLE `TIPOUSUARIO` RENAME COLUMN `idTipoUsuario` TO `IDTIPOUSUARIO`;

IF COL_LENGTH('USUARIO', 'contra') IS NOT NULL
BEGIN
    ALTER TABLE `TIPOUSUARIO` RENAME COLUMN `idTipoUsuario` TO `IDTIPOUSUARIO`;

IF COL_LENGTH('USUARIO', 'nombre') IS NOT NULL
BEGIN
    ALTER TABLE `TIPOUSUARIO` RENAME COLUMN `idTipoUsuario` TO `IDTIPOUSUARIO`;

IF COL_LENGTH('USUARIO', 'apellido') IS NOT NULL
BEGIN
    ALTER TABLE `TIPOUSUARIO` RENAME COLUMN `idTipoUsuario` TO `IDTIPOUSUARIO`;

IF COL_LENGTH('USUARIO', 'dni') IS NOT NULL
BEGIN
    ALTER TABLE `TIPOUSUARIO` RENAME COLUMN `idTipoUsuario` TO `IDTIPOUSUARIO`;

IF COL_LENGTH('USUARIO', 'fechaNacimiento') IS NOT NULL
BEGIN
    ALTER TABLE `TIPOUSUARIO` RENAME COLUMN `idTipoUsuario` TO `IDTIPOUSUARIO`;

IF COL_LENGTH('USUARIO', 'direccion') IS NOT NULL
BEGIN
    ALTER TABLE `TIPOUSUARIO` RENAME COLUMN `idTipoUsuario` TO `IDTIPOUSUARIO`;

IF COL_LENGTH('USUARIO', 'estado') IS NOT NULL
BEGIN
    ALTER TABLE `TIPOUSUARIO` RENAME COLUMN `idTipoUsuario` TO `IDTIPOUSUARIO`;

IF COL_LENGTH('USUARIO', 'distrito') IS NOT NULL
BEGIN
    ALTER TABLE `TIPOUSUARIO` RENAME COLUMN `idTipoUsuario` TO `IDTIPOUSUARIO`;

IF COL_LENGTH('USUARIO', 'colegio') IS NOT NULL
BEGIN
    ALTER TABLE `TIPOUSUARIO` RENAME COLUMN `idTipoUsuario` TO `IDTIPOUSUARIO`;

IF COL_LENGTH('USUARIO', 'grado') IS NOT NULL
BEGIN
    ALTER TABLE `TIPOUSUARIO` RENAME COLUMN `idTipoUsuario` TO `IDTIPOUSUARIO`;

IF COL_LENGTH('USUARIO', 'fechaActivo') IS NOT NULL
BEGIN
    ALTER TABLE `TIPOUSUARIO` RENAME COLUMN `idTipoUsuario` TO `IDTIPOUSUARIO`;

IF COL_LENGTH('USUARIO', 'email') IS NOT NULL
BEGIN
    ALTER TABLE `TIPOUSUARIO` RENAME COLUMN `idTipoUsuario` TO `IDTIPOUSUARIO`;

IF COL_LENGTH('USUARIO', 'telPersonal') IS NOT NULL
BEGIN
    ALTER TABLE `TIPOUSUARIO` RENAME COLUMN `idTipoUsuario` TO `IDTIPOUSUARIO`;

IF COL_LENGTH('USUARIO', 'telApoderado') IS NOT NULL
BEGIN
    ALTER TABLE `TIPOUSUARIO` RENAME COLUMN `idTipoUsuario` TO `IDTIPOUSUARIO`;

IF COL_LENGTH('USUARIO', 'situacionAcademica') IS NOT NULL
BEGIN
    ALTER TABLE `TIPOUSUARIO` RENAME COLUMN `idTipoUsuario` TO `IDTIPOUSUARIO`;

IF COL_LENGTH('USUARIO', 'idTipoUsuario') IS NOT NULL
BEGIN
    ALTER TABLE `TIPOUSUARIO` RENAME COLUMN `idTipoUsuario` TO `IDTIPOUSUARIO`;
