export const planConfig = {
  modulo: "Mantenedores",
  titulo: "Planes",
  entidad: "planes",
  pk: "IDPLAN",
  columnas: [
    { campo: "IDPLAN", etiqueta: "Código", ordenable: true },
    { campo: "NOMBRE", etiqueta: "Nombre", ordenable: true },
    { campo: "DESCRIPCION", etiqueta: "Descripción", ordenable: false },
    { campo: "TURNO_DESCRIPCION", etiqueta: "Turno", ordenable: false },
    { campo: "HORAENTRADA", etiqueta: "Hora entrada", tipo: "hora", ordenable: false },
    { campo: "TIEMPOEXTRA", etiqueta: "Tolerancia", tipo: "minutos", ordenable: false },
    { campo: "COSTOMENSUAL", etiqueta: "Costo mensual", tipo: "decimal", ordenable: true },
    { campo: "DIASASISTENCIA", etiqueta: "Días asistencia", tipo: "diasAsistencia", ordenable: false },
    { campo: "ESTADO", etiqueta: "Estado", tipo: "estado", ordenable: true },
  ],
  secciones: [
    {
      titulo: "Datos del plan",
      campos: [
        { campo: "NOMBRE", etiqueta: "Nombre", control: "text", obligatorio: true },
        {
          campo: "IDTURNO",
          etiqueta: "Turno",
          control: "select",
          catalogo: "turnos",
          obligatorio: true,
        },
        {
          campo: "HORAENTRADA",
          etiqueta: "Hora de entrada",
          control: "time",
          obligatorio: true,
          defaultValue: "08:00",
          ayuda: "Hora oficial de ingreso para este plan. Hasta esta hora (+ tolerancia) se marca presente.",
        },
        {
          campo: "TIEMPOEXTRA",
          etiqueta: "Tiempo extra (minutos)",
          control: "number",
          obligatorio: true,
          min: 0,
          max: 120,
          step: 1,
          defaultValue: 15,
          ayuda: "Minutos de tolerancia después de la hora de entrada antes de considerar tardanza.",
        },
        {
          campo: "COSTOMENSUAL",
          etiqueta: "Costo mensual",
          control: "number",
          obligatorio: true,
          min: 0,
          step: 0.01,
        },
        {
          campo: "ESTADO",
          etiqueta: "Estado",
          control: "select",
          opciones: ["Activo", "Inactivo"],
          obligatorio: true,
          defaultValue: "Activo",
        },
        {
          campo: "DIASASISTENCIA",
          etiqueta: "Días de asistencia",
          control: "diasSemana",
          obligatorio: true,
          full: true,
          defaultValue: 63,
          ayuda: "Días de la semana en que los estudiantes de este plan pueden asistir. Afecta el informe de asistencias y la referencia en horarios.",
        },
        { campo: "DESCRIPCION", etiqueta: "Descripción", control: "textarea", full: true },
      ],
    },
  ],
};

planConfig.campos = planConfig.secciones.flatMap((s) => s.campos);
